// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: common/enum.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NOTIFICATION_TYPE int32

const (
	NOTIFICATION_TYPE_UNSPECIFIED_NOTIFICATION NOTIFICATION_TYPE = 0
	NOTIFICATION_TYPE_SCHEDULED_NOTIFICATION   NOTIFICATION_TYPE = 1
)

// Enum value maps for NOTIFICATION_TYPE.
var (
	NOTIFICATION_TYPE_name = map[int32]string{
		0: "UNSPECIFIED_NOTIFICATION",
		1: "SCHEDULED_NOTIFICATION",
	}
	NOTIFICATION_TYPE_value = map[string]int32{
		"UNSPECIFIED_NOTIFICATION": 0,
		"SCHEDULED_NOTIFICATION":   1,
	}
)

func (x NOTIFICATION_TYPE) Enum() *NOTIFICATION_TYPE {
	p := new(NOTIFICATION_TYPE)
	*p = x
	return p
}

func (x NOTIFICATION_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NOTIFICATION_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_common_enum_proto_enumTypes[0].Descriptor()
}

func (NOTIFICATION_TYPE) Type() protoreflect.EnumType {
	return &file_common_enum_proto_enumTypes[0]
}

func (x NOTIFICATION_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NOTIFICATION_TYPE.Descriptor instead.
func (NOTIFICATION_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_common_enum_proto_rawDescGZIP(), []int{0}
}

var File_common_enum_proto protoreflect.FileDescriptor

const file_common_enum_proto_rawDesc = "" +
	"\n" +
	"\x11common/enum.proto\x12\x06common*M\n" +
	"\x11NOTIFICATION_TYPE\x12\x1c\n" +
	"\x18UNSPECIFIED_NOTIFICATION\x10\x00\x12\x1a\n" +
	"\x16SCHEDULED_NOTIFICATION\x10\x01B\x0eZ\fproto/commonb\x06proto3"

var (
	file_common_enum_proto_rawDescOnce sync.Once
	file_common_enum_proto_rawDescData []byte
)

func file_common_enum_proto_rawDescGZIP() []byte {
	file_common_enum_proto_rawDescOnce.Do(func() {
		file_common_enum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_enum_proto_rawDesc), len(file_common_enum_proto_rawDesc)))
	})
	return file_common_enum_proto_rawDescData
}

var file_common_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_enum_proto_goTypes = []any{
	(NOTIFICATION_TYPE)(0), // 0: common.NOTIFICATION_TYPE
}
var file_common_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_enum_proto_init() }
func file_common_enum_proto_init() {
	if File_common_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_enum_proto_rawDesc), len(file_common_enum_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_enum_proto_goTypes,
		DependencyIndexes: file_common_enum_proto_depIdxs,
		EnumInfos:         file_common_enum_proto_enumTypes,
	}.Build()
	File_common_enum_proto = out.File
	file_common_enum_proto_goTypes = nil
	file_common_enum_proto_depIdxs = nil
}
