// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: group.query.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkGroupExists = `-- name: CheckGroupExists :one
SELECT EXISTS (
    SELECT 1
    FROM groups
    WHERE id = $1 AND deleted_at IS NULL
)
`

func (q *Queries) CheckGroupExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, checkGroupExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkMemberExistsByEmail = `-- name: CheckMemberExistsByEmail :one
SELECT EXISTS (
    SELECT 1
    FROM group_members gm
    JOIN users u ON gm.user_id = u.id
    WHERE gm.group_id = $1
    AND u.email = $2
)
`

type CheckMemberExistsByEmailParams struct {
	GroupID pgtype.UUID
	Email   string
}

func (q *Queries) CheckMemberExistsByEmail(ctx context.Context, arg CheckMemberExistsByEmailParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkMemberExistsByEmail, arg.GroupID, arg.Email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countGroupMembersByGroupID = `-- name: CountGroupMembersByGroupID :one
SELECT COUNT(*)
FROM group_members
WHERE group_id = $1
`

func (q *Queries) CountGroupMembersByGroupID(ctx context.Context, groupID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countGroupMembersByGroupID, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGroupsByOwner = `-- name: CountGroupsByOwner :one
SELECT COUNT(*) 
FROM groups
WHERE owner_id = $1
AND deleted_at IS NULL
`

func (q *Queries) CountGroupsByOwner(ctx context.Context, ownerID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countGroupsByOwner, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countManagerAndMemberByGroupID = `-- name: CountManagerAndMemberByGroupID :one
SELECT COUNT(*)
FROM group_members
WHERE group_id = $1 AND role IN ('manager', 'member')
`

func (q *Queries) CountManagerAndMemberByGroupID(ctx context.Context, groupID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countManagerAndMemberByGroupID, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countViewerByGroupID = `-- name: CountViewerByGroupID :one
SELECT COUNT(*)
FROM group_members
WHERE group_id = $1 AND role = 'viewer'
`

func (q *Queries) CountViewerByGroupID(ctx context.Context, groupID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countViewerByGroupID, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (
    id,
    name,
    description,
    owner_id,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    NOW(),
    NOW()
)
RETURNING id, name, description, owner_id, created_at, updated_at, deleted_at, avatar_url
`

type CreateGroupParams struct {
	ID          pgtype.UUID
	Name        string
	Description pgtype.Text
	OwnerID     pgtype.UUID
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.OwnerID,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AvatarUrl,
	)
	return i, err
}

const createGroupMember = `-- name: CreateGroupMember :exec
INSERT INTO group_members (
    id,
    group_id,
    user_id,
    role,
    joined_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    now()
)
`

type CreateGroupMemberParams struct {
	ID      pgtype.UUID
	GroupID pgtype.UUID
	UserID  pgtype.UUID
	Role    string
}

func (q *Queries) CreateGroupMember(ctx context.Context, arg CreateGroupMemberParams) error {
	_, err := q.db.Exec(ctx, createGroupMember,
		arg.ID,
		arg.GroupID,
		arg.UserID,
		arg.Role,
	)
	return err
}

const deleteGroup = `-- name: DeleteGroup :exec
UPDATE groups 
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteGroup(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGroup, id)
	return err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, name, description, owner_id, created_at, updated_at, deleted_at, avatar_url
FROM groups
WHERE id = $1
`

func (q *Queries) GetGroupByID(ctx context.Context, id pgtype.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AvatarUrl,
	)
	return i, err
}

const getGroupsByUserID = `-- name: GetGroupsByUserID :many
SELECT 
    g.id,
    g.name,
    gm.role AS my_role,
    gm_count.member_total,
    COALESCE(g.avatar_url, '') AS avatar_url,
    g.created_at,
    g.updated_at
FROM groups g
JOIN group_members gm ON g.id = gm.group_id
JOIN (
    SELECT group_id, COUNT(*)::bigint AS member_total
    FROM group_members
    GROUP BY group_id
) gm_count ON gm_count.group_id = g.id
WHERE gm.user_id = $1
AND g.deleted_at IS NULL
ORDER BY g.created_at DESC
`

type GetGroupsByUserIDRow struct {
	ID          pgtype.UUID
	Name        string
	MyRole      string
	MemberTotal int64
	AvatarUrl   string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) GetGroupsByUserID(ctx context.Context, userID pgtype.UUID) ([]GetGroupsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getGroupsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupsByUserIDRow
	for rows.Next() {
		var i GetGroupsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MyRole,
			&i.MemberTotal,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getListUserIDByGroupID = `-- name: GetListUserIDByGroupID :many
SELECT user_id
FROM group_members
WHERE group_id = $1
`

func (q *Queries) GetListUserIDByGroupID(ctx context.Context, groupID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getListUserIDByGroupID, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var user_id pgtype.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOwnerByGroupID = `-- name: GetOwnerByGroupID :one
SELECT
    u.id AS owner_id,
    u.email AS owner_email,
    COALESCE(u.avatar_url, '') AS owner_image
FROM groups g
JOIN group_members gm ON gm.group_id = g.id
    AND gm.role = 'owner'
    AND gm.user_id = g.owner_id
JOIN users u ON u.id = g.owner_id
WHERE g.id = $1
AND g.deleted_at IS NULL
`

type GetOwnerByGroupIDRow struct {
	OwnerID    pgtype.UUID
	OwnerEmail string
	OwnerImage string
}

func (q *Queries) GetOwnerByGroupID(ctx context.Context, id pgtype.UUID) (GetOwnerByGroupIDRow, error) {
	row := q.db.QueryRow(ctx, getOwnerByGroupID, id)
	var i GetOwnerByGroupIDRow
	err := row.Scan(&i.OwnerID, &i.OwnerEmail, &i.OwnerImage)
	return i, err
}

const getRoleByGroupIDAndUserID = `-- name: GetRoleByGroupIDAndUserID :one
SELECT role
FROM group_members
WHERE group_id = $1
AND user_id = $2
`

type GetRoleByGroupIDAndUserIDParams struct {
	GroupID pgtype.UUID
	UserID  pgtype.UUID
}

func (q *Queries) GetRoleByGroupIDAndUserID(ctx context.Context, arg GetRoleByGroupIDAndUserIDParams) (string, error) {
	row := q.db.QueryRow(ctx, getRoleByGroupIDAndUserID, arg.GroupID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getSimpleUserByGroupID = `-- name: GetSimpleUserByGroupID :many
SELECT u.id, u.email, u.avatar_url
FROM group_members gm
JOIN users u ON gm.user_id = u.id
WHERE gm.group_id = $1
AND gm.role IN ('manager', 'member', 'owner')
`

type GetSimpleUserByGroupIDRow struct {
	ID        pgtype.UUID
	Email     string
	AvatarUrl pgtype.Text
}

func (q *Queries) GetSimpleUserByGroupID(ctx context.Context, groupID pgtype.UUID) ([]GetSimpleUserByGroupIDRow, error) {
	rows, err := q.db.Query(ctx, getSimpleUserByGroupID, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSimpleUserByGroupIDRow
	for rows.Next() {
		var i GetSimpleUserByGroupIDRow
		if err := rows.Scan(&i.ID, &i.Email, &i.AvatarUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSprintByGroupID = `-- name: GetSprintByGroupID :one
SELECT id, group_id, name, goal, start_date, end_date, status, velocity_work, velocity_estimate, work_deleted, created_at, updated_at
FROM sprints
WHERE group_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetSprintByGroupID(ctx context.Context, groupID pgtype.UUID) (Sprint, error) {
	row := q.db.QueryRow(ctx, getSprintByGroupID, groupID)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.Goal,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.VelocityWork,
		&i.VelocityEstimate,
		&i.WorkDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ping = `-- name: Ping :one
SELECT 1
`

func (q *Queries) Ping(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, ping)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const removeMember = `-- name: RemoveMember :exec
DELETE FROM group_members
WHERE group_id = $1
AND user_id = $2
`

type RemoveMemberParams struct {
	GroupID pgtype.UUID
	UserID  pgtype.UUID
}

func (q *Queries) RemoveMember(ctx context.Context, arg RemoveMemberParams) error {
	_, err := q.db.Exec(ctx, removeMember, arg.GroupID, arg.UserID)
	return err
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups
SET
  name = COALESCE($1, name),
  description = COALESCE($2, description),
  updated_at = NOW()
WHERE id = $3 AND deleted_at IS NULL
RETURNING id, name, description, owner_id, created_at, updated_at, deleted_at, avatar_url
`

type UpdateGroupParams struct {
	Name        pgtype.Text
	Description pgtype.Text
	ID          pgtype.UUID
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, updateGroup, arg.Name, arg.Description, arg.ID)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.AvatarUrl,
	)
	return i, err
}

const updateGroupOwner = `-- name: UpdateGroupOwner :exec
UPDATE groups
SET owner_id = $1, updated_at = NOW()
WHERE id = $2 AND deleted_at IS NULL
`

type UpdateGroupOwnerParams struct {
	OwnerID pgtype.UUID
	ID      pgtype.UUID
}

func (q *Queries) UpdateGroupOwner(ctx context.Context, arg UpdateGroupOwnerParams) error {
	_, err := q.db.Exec(ctx, updateGroupOwner, arg.OwnerID, arg.ID)
	return err
}

const updateRoleMember = `-- name: UpdateRoleMember :one
UPDATE group_members gm
SET role = $1
FROM users u
WHERE gm.group_id = $2
AND gm.user_id = $3
AND gm.user_id = u.id
RETURNING 
    u.id,
    u.email,
    u.avatar_url,
    gm.role,
    gm.joined_at
`

type UpdateRoleMemberParams struct {
	Role    string
	GroupID pgtype.UUID
	UserID  pgtype.UUID
}

type UpdateRoleMemberRow struct {
	ID        pgtype.UUID
	Email     string
	AvatarUrl pgtype.Text
	Role      string
	JoinedAt  pgtype.Timestamptz
}

func (q *Queries) UpdateRoleMember(ctx context.Context, arg UpdateRoleMemberParams) (UpdateRoleMemberRow, error) {
	row := q.db.QueryRow(ctx, updateRoleMember, arg.Role, arg.GroupID, arg.UserID)
	var i UpdateRoleMemberRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.AvatarUrl,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}
