// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: invite.query.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkPendingInvite = `-- name: CheckPendingInvite :one
SELECT EXISTS(
    SELECT 1
    FROM invites
    WHERE group_id = $1
    AND email = $2
    AND expires_at > NOW()
)
`

type CheckPendingInviteParams struct {
	GroupID pgtype.UUID
	Email   pgtype.Text
}

func (q *Queries) CheckPendingInvite(ctx context.Context, arg CheckPendingInviteParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkPendingInvite, arg.GroupID, arg.Email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (
    id,
    group_id,
    token,
    role,
    email,
    expires_at,
    created_by,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    NOW()
)
RETURNING token, expires_at, created_at
`

type CreateInviteParams struct {
	ID        pgtype.UUID
	GroupID   pgtype.UUID
	Token     string
	Role      string
	Email     pgtype.Text
	ExpiresAt pgtype.Timestamptz
	CreatedBy pgtype.UUID
}

type CreateInviteRow struct {
	Token     string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (CreateInviteRow, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.ID,
		arg.GroupID,
		arg.Token,
		arg.Role,
		arg.Email,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i CreateInviteRow
	err := row.Scan(&i.Token, &i.ExpiresAt, &i.CreatedAt)
	return i, err
}
