// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ChecklistItem struct {
	ID          pgtype.UUID
	WorkID      pgtype.UUID
	Name        string
	IsCompleted bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Comment struct {
	ID        pgtype.UUID
	WorkID    pgtype.UUID
	CreatorID pgtype.UUID
	Content   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Group struct {
	ID          pgtype.UUID
	Name        string
	Description pgtype.Text
	OwnerID     pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type GroupMember struct {
	ID       pgtype.UUID
	GroupID  pgtype.UUID
	UserID   pgtype.UUID
	Role     string
	JoinedAt pgtype.Timestamptz
}

type Invite struct {
	ID        pgtype.UUID
	GroupID   pgtype.UUID
	Token     string
	Role      string
	Email     pgtype.Text
	ExpiresAt pgtype.Timestamptz
	CreatedBy pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type Sprint struct {
	ID               pgtype.UUID
	GroupID          pgtype.UUID
	Name             string
	Goal             pgtype.Text
	StartDate        pgtype.Date
	EndDate          pgtype.Date
	Status           string
	VelocityWork     pgtype.Int4
	VelocityEstimate pgtype.Float8
	WorkDeleted      pgtype.Int4
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type User struct {
	ID        pgtype.UUID
	Email     string
	Status    string
	TimeZone  string
	CreatedAt pgtype.Timestamptz
}

type Work struct {
	ID            pgtype.UUID
	GroupID       pgtype.UUID
	SprintID      pgtype.UUID
	Name          string
	Description   pgtype.Text
	Status        string
	AssigneeID    pgtype.UUID
	CreatorID     pgtype.UUID
	EstimateHours pgtype.Float8
	StoryPoint    pgtype.Int4
	Priority      pgtype.Text
	DueDate       pgtype.Date
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}
