// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sprint.query.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelActiveSprintsByGroupID = `-- name: CancelActiveSprintsByGroupID :exec
UPDATE sprints
SET status = 'canceled', updated_at = NOW()
WHERE id = $1 AND status = 'active'
`

func (q *Queries) CancelActiveSprintsByGroupID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, cancelActiveSprintsByGroupID, id)
	return err
}

const completeActiveSprintsByGroupID = `-- name: CompleteActiveSprintsByGroupID :exec
UPDATE sprints
SET status = 'completed', updated_at = NOW()
WHERE id = $1 AND status = 'active'
`

func (q *Queries) CompleteActiveSprintsByGroupID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, completeActiveSprintsByGroupID, id)
	return err
}

const deleteDraftSprintsByGroupID = `-- name: DeleteDraftSprintsByGroupID :exec
DELETE FROM sprints
WHERE id = $1 AND status = 'draft'
`

func (q *Queries) DeleteDraftSprintsByGroupID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDraftSprintsByGroupID, id)
	return err
}

const getSprintsByGroupID = `-- name: GetSprintsByGroupID :many
SELECT id, group_id, name, goal, start_date, end_date, status, velocity_work, velocity_estimate, work_deleted, created_at, updated_at
FROM sprints
WHERE group_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetSprintsByGroupID(ctx context.Context, groupID pgtype.UUID) ([]Sprint, error) {
	rows, err := q.db.Query(ctx, getSprintsByGroupID, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sprint
	for rows.Next() {
		var i Sprint
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Name,
			&i.Goal,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.VelocityWork,
			&i.VelocityEstimate,
			&i.WorkDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
