// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sprint.query.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelActiveSprintsByGroupID = `-- name: CancelActiveSprintsByGroupID :exec
UPDATE sprints
SET status = 'canceled', updated_at = NOW()
WHERE id = $1 AND status = 'active'
`

func (q *Queries) CancelActiveSprintsByGroupID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, cancelActiveSprintsByGroupID, id)
	return err
}

const completeActiveSprintsByGroupID = `-- name: CompleteActiveSprintsByGroupID :exec
UPDATE sprints
SET status = 'completed', updated_at = NOW()
WHERE id = $1 AND status = 'active'
`

func (q *Queries) CompleteActiveSprintsByGroupID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, completeActiveSprintsByGroupID, id)
	return err
}

const createSprint = `-- name: CreateSprint :one
INSERT INTO sprints (
    id,
    group_id,
    name,
    goal,
    start_date,
    end_date,
    status,
    velocity_work,
    velocity_estimate,
    work_deleted,
    created_at,
    updated_at
) VALUES (
    $1, -- id
    $2, -- group_id
    $3, -- name
    $4, -- goal
    $5, -- start_date
    $6, -- end_date
    'draft',
    0,
    0,
    0,
    NOW(),
    NOW()
)
RETURNING
    id,
    group_id,
    name,
    goal,
    start_date,
    end_date,
    status,
    velocity_work,
    velocity_estimate,
    work_deleted,
    created_at,
    updated_at
`

type CreateSprintParams struct {
	ID        pgtype.UUID
	GroupID   pgtype.UUID
	Name      string
	Goal      pgtype.Text
	StartDate pgtype.Date
	EndDate   pgtype.Date
}

func (q *Queries) CreateSprint(ctx context.Context, arg CreateSprintParams) (Sprint, error) {
	row := q.db.QueryRow(ctx, createSprint,
		arg.ID,
		arg.GroupID,
		arg.Name,
		arg.Goal,
		arg.StartDate,
		arg.EndDate,
	)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.Goal,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.VelocityWork,
		&i.VelocityEstimate,
		&i.WorkDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDraftSprintByID = `-- name: DeleteDraftSprintByID :execrows
WITH target_sprint AS (
    SELECT sprints.id
    FROM sprints
    WHERE sprints.id = $1
      AND sprints.status = 'draft'
), deleted_works AS (
    DELETE FROM works
    WHERE works.sprint_id IN (SELECT target_sprint.id FROM target_sprint)
)
DELETE FROM sprints
WHERE sprints.id IN (SELECT target_sprint.id FROM target_sprint)
`

func (q *Queries) DeleteDraftSprintByID(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDraftSprintByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDraftSprintsByGroupID = `-- name: DeleteDraftSprintsByGroupID :exec
DELETE FROM sprints
WHERE id = $1 AND status = 'draft'
`

func (q *Queries) DeleteDraftSprintsByGroupID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDraftSprintsByGroupID, id)
	return err
}

const deleteSprint = `-- name: DeleteSprint :execrows
WITH target_sprint AS (
    SELECT sprints.id
    FROM sprints
    WHERE sprints.id = $1
      AND sprints.status = 'draft'
), moved_works AS (
    UPDATE works
    SET sprint_id = NULL,
        updated_at = NOW()
    WHERE works.sprint_id IN (SELECT target_sprint.id FROM target_sprint)
)
DELETE FROM sprints
WHERE sprints.id IN (SELECT target_sprint.id FROM target_sprint)
`

func (q *Queries) DeleteSprint(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSprint, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSimpleSprintsByGroupID = `-- name: GetSimpleSprintsByGroupID :many
SELECT id, name, status
FROM sprints
WHERE group_id = $1
`

type GetSimpleSprintsByGroupIDRow struct {
	ID     pgtype.UUID
	Name   string
	Status string
}

func (q *Queries) GetSimpleSprintsByGroupID(ctx context.Context, groupID pgtype.UUID) ([]GetSimpleSprintsByGroupIDRow, error) {
	rows, err := q.db.Query(ctx, getSimpleSprintsByGroupID, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSimpleSprintsByGroupIDRow
	for rows.Next() {
		var i GetSimpleSprintsByGroupIDRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSprintByID = `-- name: GetSprintByID :one
SELECT id, group_id, name, goal, start_date, end_date, status, velocity_work, velocity_estimate, work_deleted, created_at, updated_at
FROM sprints
WHERE id = $1
`

func (q *Queries) GetSprintByID(ctx context.Context, id pgtype.UUID) (Sprint, error) {
	row := q.db.QueryRow(ctx, getSprintByID, id)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.Goal,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.VelocityWork,
		&i.VelocityEstimate,
		&i.WorkDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSprintsByGroupID = `-- name: GetSprintsByGroupID :many
SELECT
    s.id, s.group_id, s.name, s.goal, s.start_date, s.end_date, s.status, s.velocity_work, s.velocity_estimate, s.work_deleted, s.created_at, s.updated_at,
    (
        SELECT COUNT(*)
        FROM works w
        WHERE w.sprint_id = s.id
            AND w.group_id = $1
    ) AS total_work_count,
    (
        SELECT COUNT(*)
        FROM works w
        WHERE w.sprint_id = s.id
            AND w.group_id = $1
            AND w.status = 'done'
    ) AS completed_work_count
FROM sprints s
WHERE s.group_id = $1
ORDER BY s.created_at DESC
`

type GetSprintsByGroupIDRow struct {
	ID                 pgtype.UUID
	GroupID            pgtype.UUID
	Name               string
	Goal               pgtype.Text
	StartDate          pgtype.Date
	EndDate            pgtype.Date
	Status             string
	VelocityWork       pgtype.Int4
	VelocityEstimate   pgtype.Float8
	WorkDeleted        pgtype.Int4
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	TotalWorkCount     int64
	CompletedWorkCount int64
}

func (q *Queries) GetSprintsByGroupID(ctx context.Context, groupID pgtype.UUID) ([]GetSprintsByGroupIDRow, error) {
	rows, err := q.db.Query(ctx, getSprintsByGroupID, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSprintsByGroupIDRow
	for rows.Next() {
		var i GetSprintsByGroupIDRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Name,
			&i.Goal,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.VelocityWork,
			&i.VelocityEstimate,
			&i.WorkDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalWorkCount,
			&i.CompletedWorkCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isSprintOverlap = `-- name: IsSprintOverlap :one
SELECT EXISTS (
    SELECT 1
    FROM sprints
    WHERE group_id = $1
      AND status != 'cancelled'
      AND (
            daterange(start_date, end_date, '[]')
            && daterange($2::date, $3::date, '[]')
          )
) AS is_overlap
`

type IsSprintOverlapParams struct {
	GroupID pgtype.UUID
	Column2 pgtype.Date
	Column3 pgtype.Date
}

func (q *Queries) IsSprintOverlap(ctx context.Context, arg IsSprintOverlapParams) (bool, error) {
	row := q.db.QueryRow(ctx, isSprintOverlap, arg.GroupID, arg.Column2, arg.Column3)
	var is_overlap bool
	err := row.Scan(&is_overlap)
	return is_overlap, err
}

const updateSprint = `-- name: UpdateSprint :one
UPDATE sprints
SET
        name = COALESCE($1, name),
        goal = COALESCE($2, goal),
        start_date = COALESCE($3, start_date),
        end_date = COALESCE($4, end_date),
        updated_at = NOW()
WHERE id = $5
RETURNING id, group_id, name, goal, start_date, end_date, status, velocity_work, velocity_estimate, work_deleted, created_at, updated_at
`

type UpdateSprintParams struct {
	Name      pgtype.Text
	Goal      pgtype.Text
	StartDate pgtype.Date
	EndDate   pgtype.Date
	ID        pgtype.UUID
}

func (q *Queries) UpdateSprint(ctx context.Context, arg UpdateSprintParams) (Sprint, error) {
	row := q.db.QueryRow(ctx, updateSprint,
		arg.Name,
		arg.Goal,
		arg.StartDate,
		arg.EndDate,
		arg.ID,
	)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.Goal,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.VelocityWork,
		&i.VelocityEstimate,
		&i.WorkDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSprintStatus = `-- name: UpdateSprintStatus :one
UPDATE sprints
SET
        status = $1,
        updated_at = NOW()
WHERE id = $2
RETURNING id, group_id, name, goal, start_date, end_date, status, velocity_work, velocity_estimate, work_deleted, created_at, updated_at
`

type UpdateSprintStatusParams struct {
	Status string
	ID     pgtype.UUID
}

func (q *Queries) UpdateSprintStatus(ctx context.Context, arg UpdateSprintStatusParams) (Sprint, error) {
	row := q.db.QueryRow(ctx, updateSprintStatus, arg.Status, arg.ID)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.Goal,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.VelocityWork,
		&i.VelocityEstimate,
		&i.WorkDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
