// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sprint.query.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelActiveSprintsByGroupID = `-- name: CancelActiveSprintsByGroupID :exec
UPDATE sprints
SET status = 'canceled', updated_at = NOW()
WHERE id = $1 AND status = 'active'
`

func (q *Queries) CancelActiveSprintsByGroupID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, cancelActiveSprintsByGroupID, id)
	return err
}

const completeActiveSprintsByGroupID = `-- name: CompleteActiveSprintsByGroupID :exec
UPDATE sprints
SET status = 'completed', updated_at = NOW()
WHERE id = $1 AND status = 'active'
`

func (q *Queries) CompleteActiveSprintsByGroupID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, completeActiveSprintsByGroupID, id)
	return err
}

const createSprint = `-- name: CreateSprint :one
INSERT INTO sprints (
    id,
    group_id,
    name,
    goal,
    start_date,
    end_date,
    status,
    velocity_work,
    velocity_estimate,
    work_deleted,
    created_at,
    updated_at
) VALUES (
    $1, -- id
    $2, -- group_id
    $3, -- name
    $4, -- goal
    $5, -- start_date
    $6, -- end_date
    'draft',
    0,
    0,
    0,
    NOW(),
    NOW()
)
RETURNING
    id,
    group_id,
    name,
    goal,
    start_date,
    end_date,
    status,
    velocity_work,
    velocity_estimate,
    work_deleted,
    created_at,
    updated_at
`

type CreateSprintParams struct {
	ID        pgtype.UUID
	GroupID   pgtype.UUID
	Name      string
	Goal      pgtype.Text
	StartDate pgtype.Date
	EndDate   pgtype.Date
}

func (q *Queries) CreateSprint(ctx context.Context, arg CreateSprintParams) (Sprint, error) {
	row := q.db.QueryRow(ctx, createSprint,
		arg.ID,
		arg.GroupID,
		arg.Name,
		arg.Goal,
		arg.StartDate,
		arg.EndDate,
	)
	var i Sprint
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.Goal,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.VelocityWork,
		&i.VelocityEstimate,
		&i.WorkDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDraftSprintsByGroupID = `-- name: DeleteDraftSprintsByGroupID :exec
DELETE FROM sprints
WHERE id = $1 AND status = 'draft'
`

func (q *Queries) DeleteDraftSprintsByGroupID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDraftSprintsByGroupID, id)
	return err
}

const getSprintsByGroupID = `-- name: GetSprintsByGroupID :many
SELECT id, group_id, name, goal, start_date, end_date, status, velocity_work, velocity_estimate, work_deleted, created_at, updated_at
FROM sprints
WHERE group_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetSprintsByGroupID(ctx context.Context, groupID pgtype.UUID) ([]Sprint, error) {
	rows, err := q.db.Query(ctx, getSprintsByGroupID, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sprint
	for rows.Next() {
		var i Sprint
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Name,
			&i.Goal,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.VelocityWork,
			&i.VelocityEstimate,
			&i.WorkDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isSprintOverlap = `-- name: IsSprintOverlap :one
SELECT EXISTS (
    SELECT 1
    FROM sprints
    WHERE group_id = $1
      AND status != 'cancelled'
      AND (
            daterange(start_date, end_date, '[]')
            && daterange($2::date, $3::date, '[]')
          )
) AS is_overlap
`

type IsSprintOverlapParams struct {
	GroupID pgtype.UUID
	Column2 pgtype.Date
	Column3 pgtype.Date
}

func (q *Queries) IsSprintOverlap(ctx context.Context, arg IsSprintOverlapParams) (bool, error) {
	row := q.db.QueryRow(ctx, isSprintOverlap, arg.GroupID, arg.Column2, arg.Column3)
	var is_overlap bool
	err := row.Scan(&is_overlap)
	return is_overlap, err
}
