// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.query.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getListGroupMembers = `-- name: GetListGroupMembers :many
SELECT 
    u.id,
    u.email,
    u.avatar_url AS avatar,
    gm.role,
    gm.joined_at
FROM group_members gm
JOIN users u ON gm.user_id = u.id
WHERE gm.group_id = $1
ORDER BY gm.joined_at
`

type GetListGroupMembersRow struct {
	ID       pgtype.UUID
	Email    string
	Avatar   pgtype.Text
	Role     string
	JoinedAt pgtype.Timestamptz
}

func (q *Queries) GetListGroupMembers(ctx context.Context, groupID pgtype.UUID) ([]GetListGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, getListGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetListGroupMembersRow
	for rows.Next() {
		var i GetListGroupMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Avatar,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, status, created_at, avatar_url, has_email_notification, has_push_notification
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Status,
		&i.CreatedAt,
		&i.AvatarUrl,
		&i.HasEmailNotification,
		&i.HasPushNotification,
	)
	return i, err
}

const getUserWithPermissionByID = `-- name: GetUserWithPermissionByID :one
SELECT
    u.id,
    u.email,
    u.status,
    u.created_at,
    gm.group_id,
    gm.role,
    gm.joined_at
FROM users u
JOIN group_members gm
    ON gm.user_id = u.id
WHERE gm.group_id = $1
AND u.id = $2
LIMIT 1
`

type GetUserWithPermissionByIDParams struct {
	GroupID pgtype.UUID
	ID      pgtype.UUID
}

type GetUserWithPermissionByIDRow struct {
	ID        pgtype.UUID
	Email     string
	Status    string
	CreatedAt pgtype.Timestamptz
	GroupID   pgtype.UUID
	Role      string
	JoinedAt  pgtype.Timestamptz
}

func (q *Queries) GetUserWithPermissionByID(ctx context.Context, arg GetUserWithPermissionByIDParams) (GetUserWithPermissionByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserWithPermissionByID, arg.GroupID, arg.ID)
	var i GetUserWithPermissionByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Status,
		&i.CreatedAt,
		&i.GroupID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO users (
    id,
    email,
    status,
    created_at,
    avatar_url,
    has_email_notification,
    has_push_notification
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
ON CONFLICT (id) DO UPDATE
SET
    email = EXCLUDED.email,
    status = EXCLUDED.status,
    avatar_url = EXCLUDED.avatar_url,
    has_email_notification = EXCLUDED.has_email_notification,
    has_push_notification = EXCLUDED.has_push_notification
`

type UpsertUserParams struct {
	ID                   pgtype.UUID
	Email                string
	Status               string
	CreatedAt            pgtype.Timestamptz
	AvatarUrl            pgtype.Text
	HasEmailNotification bool
	HasPushNotification  bool
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.Exec(ctx, upsertUser,
		arg.ID,
		arg.Email,
		arg.Status,
		arg.CreatedAt,
		arg.AvatarUrl,
		arg.HasEmailNotification,
		arg.HasPushNotification,
	)
	return err
}
