// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: work.query.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const unassignWorksByMember = `-- name: UnassignWorksByMember :exec
UPDATE works
SET assignee_id = NULL
WHERE group_id = $1
AND assignee_id = $2
`

type UnassignWorksByMemberParams struct {
	GroupID    pgtype.UUID
	AssigneeID pgtype.UUID
}

func (q *Queries) UnassignWorksByMember(ctx context.Context, arg UnassignWorksByMemberParams) error {
	_, err := q.db.Exec(ctx, unassignWorksByMember, arg.GroupID, arg.AssigneeID)
	return err
}
