// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: team_service/group.proto

package team_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	common "team_service/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	Description   *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupRequest) Reset() {
	*x = CreateGroupRequest{}
	mi := &file_team_service_group_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupRequest) ProtoMessage() {}

func (x *CreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_group_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_team_service_group_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGroupRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type CreateGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *GroupMessage          `protobuf:"bytes,1,opt,name=group,proto3" json:"group"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupResponse) Reset() {
	*x = CreateGroupResponse{}
	mi := &file_team_service_group_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupResponse) ProtoMessage() {}

func (x *CreateGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_group_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupResponse.ProtoReflect.Descriptor instead.
func (*CreateGroupResponse) Descriptor() ([]byte, []int) {
	return file_team_service_group_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGroupResponse) GetGroup() *GroupMessage {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *CreateGroupResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *GroupMessage          `protobuf:"bytes,1,opt,name=group,proto3" json:"group"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupResponse) Reset() {
	*x = GetGroupResponse{}
	mi := &file_team_service_group_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupResponse) ProtoMessage() {}

func (x *GetGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_group_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupResponse.ProtoReflect.Descriptor instead.
func (*GetGroupResponse) Descriptor() ([]byte, []int) {
	return file_team_service_group_proto_rawDescGZIP(), []int{2}
}

func (x *GetGroupResponse) GetGroup() *GroupMessage {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *GetGroupResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type UpdateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupRequest) Reset() {
	*x = UpdateGroupRequest{}
	mi := &file_team_service_group_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupRequest) ProtoMessage() {}

func (x *UpdateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_group_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupRequest.ProtoReflect.Descriptor instead.
func (*UpdateGroupRequest) Descriptor() ([]byte, []int) {
	return file_team_service_group_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateGroupRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateGroupRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateGroupRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type UpdateGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *GroupMessage          `protobuf:"bytes,1,opt,name=group,proto3" json:"group"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupResponse) Reset() {
	*x = UpdateGroupResponse{}
	mi := &file_team_service_group_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupResponse) ProtoMessage() {}

func (x *UpdateGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_group_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupResponse.ProtoReflect.Descriptor instead.
func (*UpdateGroupResponse) Descriptor() ([]byte, []int) {
	return file_team_service_group_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateGroupResponse) GetGroup() *GroupMessage {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *UpdateGroupResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type DeleteGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupResponse) Reset() {
	*x = DeleteGroupResponse{}
	mi := &file_team_service_group_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupResponse) ProtoMessage() {}

func (x *DeleteGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_group_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupResponse.ProtoReflect.Descriptor instead.
func (*DeleteGroupResponse) Descriptor() ([]byte, []int) {
	return file_team_service_group_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteGroupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteGroupResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type ListMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersRequest) Reset() {
	*x = ListMembersRequest{}
	mi := &file_team_service_group_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersRequest) ProtoMessage() {}

func (x *ListMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_group_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersRequest.ProtoReflect.Descriptor instead.
func (*ListMembersRequest) Descriptor() ([]byte, []int) {
	return file_team_service_group_proto_rawDescGZIP(), []int{6}
}

func (x *ListMembersRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type ListMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*MemberMessage       `protobuf:"bytes,1,rep,name=members,proto3" json:"members"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total"`
	Error         *Error                 `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersResponse) Reset() {
	*x = ListMembersResponse{}
	mi := &file_team_service_group_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersResponse) ProtoMessage() {}

func (x *ListMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_group_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersResponse.ProtoReflect.Descriptor instead.
func (*ListMembersResponse) Descriptor() ([]byte, []int) {
	return file_team_service_group_proto_rawDescGZIP(), []int{7}
}

func (x *ListMembersResponse) GetMembers() []*MemberMessage {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *ListMembersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListMembersResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type UpdateMemberRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id"`
	MemberId      string                 `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id"`
	NewRole       GroupRole              `protobuf:"varint,3,opt,name=new_role,json=newRole,proto3,enum=team_service.GroupRole" json:"new_role"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMemberRoleRequest) Reset() {
	*x = UpdateMemberRoleRequest{}
	mi := &file_team_service_group_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMemberRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemberRoleRequest) ProtoMessage() {}

func (x *UpdateMemberRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_group_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemberRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateMemberRoleRequest) Descriptor() ([]byte, []int) {
	return file_team_service_group_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateMemberRoleRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *UpdateMemberRoleRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *UpdateMemberRoleRequest) GetNewRole() GroupRole {
	if x != nil {
		return x.NewRole
	}
	return GroupRole_GROUP_ROLE_UNSPECIFIED
}

type UpdateMemberRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *MemberMessage         `protobuf:"bytes,1,opt,name=member,proto3" json:"member"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMemberRoleResponse) Reset() {
	*x = UpdateMemberRoleResponse{}
	mi := &file_team_service_group_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMemberRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemberRoleResponse) ProtoMessage() {}

func (x *UpdateMemberRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_group_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemberRoleResponse.ProtoReflect.Descriptor instead.
func (*UpdateMemberRoleResponse) Descriptor() ([]byte, []int) {
	return file_team_service_group_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateMemberRoleResponse) GetMember() *MemberMessage {
	if x != nil {
		return x.Member
	}
	return nil
}

func (x *UpdateMemberRoleResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type RemoveMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id"`
	MemberId      string                 `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberRequest) Reset() {
	*x = RemoveMemberRequest{}
	mi := &file_team_service_group_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberRequest) ProtoMessage() {}

func (x *RemoveMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_group_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveMemberRequest) Descriptor() ([]byte, []int) {
	return file_team_service_group_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveMemberRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *RemoveMemberRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

type RemoveMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberResponse) Reset() {
	*x = RemoveMemberResponse{}
	mi := &file_team_service_group_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberResponse) ProtoMessage() {}

func (x *RemoveMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_group_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberResponse.ProtoReflect.Descriptor instead.
func (*RemoveMemberResponse) Descriptor() ([]byte, []int) {
	return file_team_service_group_proto_rawDescGZIP(), []int{11}
}

func (x *RemoveMemberResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveMemberResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type CreateInviteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id"`
	Email         *string                `protobuf:"bytes,2,opt,name=email,proto3,oneof" json:"email"`
	Role          GroupRole              `protobuf:"varint,3,opt,name=role,proto3,enum=team_service.GroupRole" json:"role"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInviteRequest) Reset() {
	*x = CreateInviteRequest{}
	mi := &file_team_service_group_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInviteRequest) ProtoMessage() {}

func (x *CreateInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_group_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInviteRequest.ProtoReflect.Descriptor instead.
func (*CreateInviteRequest) Descriptor() ([]byte, []int) {
	return file_team_service_group_proto_rawDescGZIP(), []int{12}
}

func (x *CreateInviteRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *CreateInviteRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *CreateInviteRequest) GetRole() GroupRole {
	if x != nil {
		return x.Role
	}
	return GroupRole_GROUP_ROLE_UNSPECIFIED
}

type CreateInviteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invite        *InviteMessage         `protobuf:"bytes,1,opt,name=invite,proto3" json:"invite"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInviteResponse) Reset() {
	*x = CreateInviteResponse{}
	mi := &file_team_service_group_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInviteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInviteResponse) ProtoMessage() {}

func (x *CreateInviteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_group_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInviteResponse.ProtoReflect.Descriptor instead.
func (*CreateInviteResponse) Descriptor() ([]byte, []int) {
	return file_team_service_group_proto_rawDescGZIP(), []int{13}
}

func (x *CreateInviteResponse) GetInvite() *InviteMessage {
	if x != nil {
		return x.Invite
	}
	return nil
}

func (x *CreateInviteResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type AcceptInviteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptInviteRequest) Reset() {
	*x = AcceptInviteRequest{}
	mi := &file_team_service_group_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptInviteRequest) ProtoMessage() {}

func (x *AcceptInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_group_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptInviteRequest.ProtoReflect.Descriptor instead.
func (*AcceptInviteRequest) Descriptor() ([]byte, []int) {
	return file_team_service_group_proto_rawDescGZIP(), []int{14}
}

func (x *AcceptInviteRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type AcceptInviteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      string                 `protobuf:"bytes,1,opt,name=location,proto3" json:"location"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptInviteResponse) Reset() {
	*x = AcceptInviteResponse{}
	mi := &file_team_service_group_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptInviteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptInviteResponse) ProtoMessage() {}

func (x *AcceptInviteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_group_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptInviteResponse.ProtoReflect.Descriptor instead.
func (*AcceptInviteResponse) Descriptor() ([]byte, []int) {
	return file_team_service_group_proto_rawDescGZIP(), []int{15}
}

func (x *AcceptInviteResponse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *AcceptInviteResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type ListGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*GroupMessage        `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total"`
	Error         *Error                 `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsResponse) Reset() {
	*x = ListGroupsResponse{}
	mi := &file_team_service_group_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsResponse) ProtoMessage() {}

func (x *ListGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_group_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListGroupsResponse) Descriptor() ([]byte, []int) {
	return file_team_service_group_proto_rawDescGZIP(), []int{16}
}

func (x *ListGroupsResponse) GetGroups() []*GroupMessage {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *ListGroupsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListGroupsResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type ConfirmDeleteGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmDeleteGroupRequest) Reset() {
	*x = ConfirmDeleteGroupRequest{}
	mi := &file_team_service_group_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmDeleteGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmDeleteGroupRequest) ProtoMessage() {}

func (x *ConfirmDeleteGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_group_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmDeleteGroupRequest.ProtoReflect.Descriptor instead.
func (*ConfirmDeleteGroupRequest) Descriptor() ([]byte, []int) {
	return file_team_service_group_proto_rawDescGZIP(), []int{17}
}

func (x *ConfirmDeleteGroupRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ConfirmDeleteGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	DeleteAt      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=delete_at,json=deleteAt,proto3" json:"delete_at"`
	Error         *Error                 `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmDeleteGroupResponse) Reset() {
	*x = ConfirmDeleteGroupResponse{}
	mi := &file_team_service_group_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmDeleteGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmDeleteGroupResponse) ProtoMessage() {}

func (x *ConfirmDeleteGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_group_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmDeleteGroupResponse.ProtoReflect.Descriptor instead.
func (*ConfirmDeleteGroupResponse) Descriptor() ([]byte, []int) {
	return file_team_service_group_proto_rawDescGZIP(), []int{18}
}

func (x *ConfirmDeleteGroupResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConfirmDeleteGroupResponse) GetDeleteAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeleteAt
	}
	return nil
}

func (x *ConfirmDeleteGroupResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetSimpleUserByGroupIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*SimpleUserMessage   `protobuf:"bytes,1,rep,name=users,proto3" json:"users"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSimpleUserByGroupIDResponse) Reset() {
	*x = GetSimpleUserByGroupIDResponse{}
	mi := &file_team_service_group_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSimpleUserByGroupIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSimpleUserByGroupIDResponse) ProtoMessage() {}

func (x *GetSimpleUserByGroupIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_group_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSimpleUserByGroupIDResponse.ProtoReflect.Descriptor instead.
func (*GetSimpleUserByGroupIDResponse) Descriptor() ([]byte, []int) {
	return file_team_service_group_proto_rawDescGZIP(), []int{19}
}

func (x *GetSimpleUserByGroupIDResponse) GetUsers() []*SimpleUserMessage {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *GetSimpleUserByGroupIDResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type PresignFileItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresignFileItem) Reset() {
	*x = PresignFileItem{}
	mi := &file_team_service_group_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresignFileItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresignFileItem) ProtoMessage() {}

func (x *PresignFileItem) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_group_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresignFileItem.ProtoReflect.Descriptor instead.
func (*PresignFileItem) Descriptor() ([]byte, []int) {
	return file_team_service_group_proto_rawDescGZIP(), []int{20}
}

func (x *PresignFileItem) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *PresignFileItem) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *PresignFileItem) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type GeneratePresignedURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*PresignFileItem     `protobuf:"bytes,1,rep,name=files,proto3" json:"files"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratePresignedURLsRequest) Reset() {
	*x = GeneratePresignedURLsRequest{}
	mi := &file_team_service_group_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratePresignedURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePresignedURLsRequest) ProtoMessage() {}

func (x *GeneratePresignedURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_group_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePresignedURLsRequest.ProtoReflect.Descriptor instead.
func (*GeneratePresignedURLsRequest) Descriptor() ([]byte, []int) {
	return file_team_service_group_proto_rawDescGZIP(), []int{21}
}

func (x *GeneratePresignedURLsRequest) GetFiles() []*PresignFileItem {
	if x != nil {
		return x.Files
	}
	return nil
}

type PresignedFileItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index"`
	PresignedUrl  string                 `protobuf:"bytes,2,opt,name=presigned_url,json=presignedUrl,proto3" json:"presigned_url"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresignedFileItem) Reset() {
	*x = PresignedFileItem{}
	mi := &file_team_service_group_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresignedFileItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresignedFileItem) ProtoMessage() {}

func (x *PresignedFileItem) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_group_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresignedFileItem.ProtoReflect.Descriptor instead.
func (*PresignedFileItem) Descriptor() ([]byte, []int) {
	return file_team_service_group_proto_rawDescGZIP(), []int{22}
}

func (x *PresignedFileItem) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *PresignedFileItem) GetPresignedUrl() string {
	if x != nil {
		return x.PresignedUrl
	}
	return ""
}

type GeneratePresignedURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*PresignedFileItem   `protobuf:"bytes,1,rep,name=files,proto3" json:"files"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratePresignedURLsResponse) Reset() {
	*x = GeneratePresignedURLsResponse{}
	mi := &file_team_service_group_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratePresignedURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePresignedURLsResponse) ProtoMessage() {}

func (x *GeneratePresignedURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_group_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePresignedURLsResponse.ProtoReflect.Descriptor instead.
func (*GeneratePresignedURLsResponse) Descriptor() ([]byte, []int) {
	return file_team_service_group_proto_rawDescGZIP(), []int{23}
}

func (x *GeneratePresignedURLsResponse) GetFiles() []*PresignedFileItem {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *GeneratePresignedURLsResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_team_service_group_proto protoreflect.FileDescriptor

const file_team_service_group_proto_rawDesc = "" +
	"\n" +
	"\x18team_service/group.proto\x12\fteam_service\x1a\x1eteam_service/common.team.proto\x1a\x13common/common.proto\x1a\x12common/error.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"_\n" +
	"\x12CreateGroupRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01B\x0e\n" +
	"\f_description\"\x81\x01\n" +
	"\x13CreateGroupResponse\x120\n" +
	"\x05group\x18\x01 \x01(\v2\x1a.team_service.GroupMessageR\x05group\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x13.team_service.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"~\n" +
	"\x10GetGroupResponse\x120\n" +
	"\x05group\x18\x01 \x01(\v2\x1a.team_service.GroupMessageR\x05group\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x13.team_service.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"}\n" +
	"\x12UpdateGroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_description\"\x81\x01\n" +
	"\x13UpdateGroupResponse\x120\n" +
	"\x05group\x18\x01 \x01(\v2\x1a.team_service.GroupMessageR\x05group\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x13.team_service.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"i\n" +
	"\x13DeleteGroupResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x13.team_service.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"/\n" +
	"\x12ListMembersRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\"\x9c\x01\n" +
	"\x13ListMembersResponse\x125\n" +
	"\amembers\x18\x01 \x03(\v2\x1b.team_service.MemberMessageR\amembers\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12.\n" +
	"\x05error\x18\x03 \x01(\v2\x13.team_service.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\x85\x01\n" +
	"\x17UpdateMemberRoleRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\tR\bmemberId\x122\n" +
	"\bnew_role\x18\x03 \x01(\x0e2\x17.team_service.GroupRoleR\anewRole\"\x89\x01\n" +
	"\x18UpdateMemberRoleResponse\x123\n" +
	"\x06member\x18\x01 \x01(\v2\x1b.team_service.MemberMessageR\x06member\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x13.team_service.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"M\n" +
	"\x13RemoveMemberRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\tR\bmemberId\"j\n" +
	"\x14RemoveMemberResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x13.team_service.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\x82\x01\n" +
	"\x13CreateInviteRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x19\n" +
	"\x05email\x18\x02 \x01(\tH\x00R\x05email\x88\x01\x01\x12+\n" +
	"\x04role\x18\x03 \x01(\x0e2\x17.team_service.GroupRoleR\x04roleB\b\n" +
	"\x06_email\"\x85\x01\n" +
	"\x14CreateInviteResponse\x123\n" +
	"\x06invite\x18\x01 \x01(\v2\x1b.team_service.InviteMessageR\x06invite\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x13.team_service.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\")\n" +
	"\x13AcceptInviteRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"l\n" +
	"\x14AcceptInviteResponse\x12\x1a\n" +
	"\blocation\x18\x01 \x01(\tR\blocation\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x13.team_service.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\x98\x01\n" +
	"\x12ListGroupsResponse\x122\n" +
	"\x06groups\x18\x01 \x03(\v2\x1a.team_service.GroupMessageR\x06groups\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12.\n" +
	"\x05error\x18\x03 \x01(\v2\x13.team_service.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"1\n" +
	"\x19ConfirmDeleteGroupRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x9f\x01\n" +
	"\x1aConfirmDeleteGroupResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x127\n" +
	"\tdelete_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bdeleteAt\x12.\n" +
	"\x05error\x18\x03 \x01(\v2\x13.team_service.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\x91\x01\n" +
	"\x1eGetSimpleUserByGroupIDResponse\x125\n" +
	"\x05users\x18\x01 \x03(\v2\x1f.team_service.SimpleUserMessageR\x05users\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x13.team_service.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"g\n" +
	"\x0fPresignFileItem\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\"S\n" +
	"\x1cGeneratePresignedURLsRequest\x123\n" +
	"\x05files\x18\x01 \x03(\v2\x1d.team_service.PresignFileItemR\x05files\"N\n" +
	"\x11PresignedFileItem\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12#\n" +
	"\rpresigned_url\x18\x02 \x01(\tR\fpresignedUrl\"\x90\x01\n" +
	"\x1dGeneratePresignedURLsResponse\x125\n" +
	"\x05files\x18\x01 \x03(\v2\x1f.team_service.PresignedFileItemR\x05files\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x13.team_service.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error2\xbb\b\n" +
	"\fGroupService\x123\n" +
	"\x04Ping\x12\x14.common.EmptyRequest\x1a\x15.common.EmptyResponse\x12R\n" +
	"\vCreateGroup\x12 .team_service.CreateGroupRequest\x1a!.team_service.CreateGroupResponse\x12=\n" +
	"\bGetGroup\x12\x11.common.IDRequest\x1a\x1e.team_service.GetGroupResponse\x12A\n" +
	"\n" +
	"ListGroups\x12\x11.common.IDRequest\x1a .team_service.ListGroupsResponse\x12R\n" +
	"\vUpdateGroup\x12 .team_service.UpdateGroupRequest\x1a!.team_service.UpdateGroupResponse\x12C\n" +
	"\vDeleteGroup\x12\x11.common.IDRequest\x1a!.team_service.DeleteGroupResponse\x12R\n" +
	"\vListMembers\x12 .team_service.ListMembersRequest\x1a!.team_service.ListMembersResponse\x12a\n" +
	"\x10UpdateMemberRole\x12%.team_service.UpdateMemberRoleRequest\x1a&.team_service.UpdateMemberRoleResponse\x12U\n" +
	"\fRemoveMember\x12!.team_service.RemoveMemberRequest\x1a\".team_service.RemoveMemberResponse\x12U\n" +
	"\fCreateInvite\x12!.team_service.CreateInviteRequest\x1a\".team_service.CreateInviteResponse\x12U\n" +
	"\fAcceptInvite\x12!.team_service.AcceptInviteRequest\x1a\".team_service.AcceptInviteResponse\x12Y\n" +
	"\x16GetSimpleUserByGroupID\x12\x11.common.IDRequest\x1a,.team_service.GetSimpleUserByGroupIDResponse\x12p\n" +
	"\x15GeneratePresignedURLs\x12*.team_service.GeneratePresignedURLsRequest\x1a+.team_service.GeneratePresignedURLsResponseB\x14Z\x12proto/team_serviceb\x06proto3"

var (
	file_team_service_group_proto_rawDescOnce sync.Once
	file_team_service_group_proto_rawDescData []byte
)

func file_team_service_group_proto_rawDescGZIP() []byte {
	file_team_service_group_proto_rawDescOnce.Do(func() {
		file_team_service_group_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_team_service_group_proto_rawDesc), len(file_team_service_group_proto_rawDesc)))
	})
	return file_team_service_group_proto_rawDescData
}

var file_team_service_group_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_team_service_group_proto_goTypes = []any{
	(*CreateGroupRequest)(nil),             // 0: team_service.CreateGroupRequest
	(*CreateGroupResponse)(nil),            // 1: team_service.CreateGroupResponse
	(*GetGroupResponse)(nil),               // 2: team_service.GetGroupResponse
	(*UpdateGroupRequest)(nil),             // 3: team_service.UpdateGroupRequest
	(*UpdateGroupResponse)(nil),            // 4: team_service.UpdateGroupResponse
	(*DeleteGroupResponse)(nil),            // 5: team_service.DeleteGroupResponse
	(*ListMembersRequest)(nil),             // 6: team_service.ListMembersRequest
	(*ListMembersResponse)(nil),            // 7: team_service.ListMembersResponse
	(*UpdateMemberRoleRequest)(nil),        // 8: team_service.UpdateMemberRoleRequest
	(*UpdateMemberRoleResponse)(nil),       // 9: team_service.UpdateMemberRoleResponse
	(*RemoveMemberRequest)(nil),            // 10: team_service.RemoveMemberRequest
	(*RemoveMemberResponse)(nil),           // 11: team_service.RemoveMemberResponse
	(*CreateInviteRequest)(nil),            // 12: team_service.CreateInviteRequest
	(*CreateInviteResponse)(nil),           // 13: team_service.CreateInviteResponse
	(*AcceptInviteRequest)(nil),            // 14: team_service.AcceptInviteRequest
	(*AcceptInviteResponse)(nil),           // 15: team_service.AcceptInviteResponse
	(*ListGroupsResponse)(nil),             // 16: team_service.ListGroupsResponse
	(*ConfirmDeleteGroupRequest)(nil),      // 17: team_service.ConfirmDeleteGroupRequest
	(*ConfirmDeleteGroupResponse)(nil),     // 18: team_service.ConfirmDeleteGroupResponse
	(*GetSimpleUserByGroupIDResponse)(nil), // 19: team_service.GetSimpleUserByGroupIDResponse
	(*PresignFileItem)(nil),                // 20: team_service.PresignFileItem
	(*GeneratePresignedURLsRequest)(nil),   // 21: team_service.GeneratePresignedURLsRequest
	(*PresignedFileItem)(nil),              // 22: team_service.PresignedFileItem
	(*GeneratePresignedURLsResponse)(nil),  // 23: team_service.GeneratePresignedURLsResponse
	(*GroupMessage)(nil),                   // 24: team_service.GroupMessage
	(*Error)(nil),                          // 25: team_service.Error
	(*MemberMessage)(nil),                  // 26: team_service.MemberMessage
	(GroupRole)(0),                         // 27: team_service.GroupRole
	(*InviteMessage)(nil),                  // 28: team_service.InviteMessage
	(*timestamppb.Timestamp)(nil),          // 29: google.protobuf.Timestamp
	(*SimpleUserMessage)(nil),              // 30: team_service.SimpleUserMessage
	(*common.EmptyRequest)(nil),            // 31: common.EmptyRequest
	(*common.IDRequest)(nil),               // 32: common.IDRequest
	(*common.EmptyResponse)(nil),           // 33: common.EmptyResponse
}
var file_team_service_group_proto_depIdxs = []int32{
	24, // 0: team_service.CreateGroupResponse.group:type_name -> team_service.GroupMessage
	25, // 1: team_service.CreateGroupResponse.error:type_name -> team_service.Error
	24, // 2: team_service.GetGroupResponse.group:type_name -> team_service.GroupMessage
	25, // 3: team_service.GetGroupResponse.error:type_name -> team_service.Error
	24, // 4: team_service.UpdateGroupResponse.group:type_name -> team_service.GroupMessage
	25, // 5: team_service.UpdateGroupResponse.error:type_name -> team_service.Error
	25, // 6: team_service.DeleteGroupResponse.error:type_name -> team_service.Error
	26, // 7: team_service.ListMembersResponse.members:type_name -> team_service.MemberMessage
	25, // 8: team_service.ListMembersResponse.error:type_name -> team_service.Error
	27, // 9: team_service.UpdateMemberRoleRequest.new_role:type_name -> team_service.GroupRole
	26, // 10: team_service.UpdateMemberRoleResponse.member:type_name -> team_service.MemberMessage
	25, // 11: team_service.UpdateMemberRoleResponse.error:type_name -> team_service.Error
	25, // 12: team_service.RemoveMemberResponse.error:type_name -> team_service.Error
	27, // 13: team_service.CreateInviteRequest.role:type_name -> team_service.GroupRole
	28, // 14: team_service.CreateInviteResponse.invite:type_name -> team_service.InviteMessage
	25, // 15: team_service.CreateInviteResponse.error:type_name -> team_service.Error
	25, // 16: team_service.AcceptInviteResponse.error:type_name -> team_service.Error
	24, // 17: team_service.ListGroupsResponse.groups:type_name -> team_service.GroupMessage
	25, // 18: team_service.ListGroupsResponse.error:type_name -> team_service.Error
	29, // 19: team_service.ConfirmDeleteGroupResponse.delete_at:type_name -> google.protobuf.Timestamp
	25, // 20: team_service.ConfirmDeleteGroupResponse.error:type_name -> team_service.Error
	30, // 21: team_service.GetSimpleUserByGroupIDResponse.users:type_name -> team_service.SimpleUserMessage
	25, // 22: team_service.GetSimpleUserByGroupIDResponse.error:type_name -> team_service.Error
	20, // 23: team_service.GeneratePresignedURLsRequest.files:type_name -> team_service.PresignFileItem
	22, // 24: team_service.GeneratePresignedURLsResponse.files:type_name -> team_service.PresignedFileItem
	25, // 25: team_service.GeneratePresignedURLsResponse.error:type_name -> team_service.Error
	31, // 26: team_service.GroupService.Ping:input_type -> common.EmptyRequest
	0,  // 27: team_service.GroupService.CreateGroup:input_type -> team_service.CreateGroupRequest
	32, // 28: team_service.GroupService.GetGroup:input_type -> common.IDRequest
	32, // 29: team_service.GroupService.ListGroups:input_type -> common.IDRequest
	3,  // 30: team_service.GroupService.UpdateGroup:input_type -> team_service.UpdateGroupRequest
	32, // 31: team_service.GroupService.DeleteGroup:input_type -> common.IDRequest
	6,  // 32: team_service.GroupService.ListMembers:input_type -> team_service.ListMembersRequest
	8,  // 33: team_service.GroupService.UpdateMemberRole:input_type -> team_service.UpdateMemberRoleRequest
	10, // 34: team_service.GroupService.RemoveMember:input_type -> team_service.RemoveMemberRequest
	12, // 35: team_service.GroupService.CreateInvite:input_type -> team_service.CreateInviteRequest
	14, // 36: team_service.GroupService.AcceptInvite:input_type -> team_service.AcceptInviteRequest
	32, // 37: team_service.GroupService.GetSimpleUserByGroupID:input_type -> common.IDRequest
	21, // 38: team_service.GroupService.GeneratePresignedURLs:input_type -> team_service.GeneratePresignedURLsRequest
	33, // 39: team_service.GroupService.Ping:output_type -> common.EmptyResponse
	1,  // 40: team_service.GroupService.CreateGroup:output_type -> team_service.CreateGroupResponse
	2,  // 41: team_service.GroupService.GetGroup:output_type -> team_service.GetGroupResponse
	16, // 42: team_service.GroupService.ListGroups:output_type -> team_service.ListGroupsResponse
	4,  // 43: team_service.GroupService.UpdateGroup:output_type -> team_service.UpdateGroupResponse
	5,  // 44: team_service.GroupService.DeleteGroup:output_type -> team_service.DeleteGroupResponse
	7,  // 45: team_service.GroupService.ListMembers:output_type -> team_service.ListMembersResponse
	9,  // 46: team_service.GroupService.UpdateMemberRole:output_type -> team_service.UpdateMemberRoleResponse
	11, // 47: team_service.GroupService.RemoveMember:output_type -> team_service.RemoveMemberResponse
	13, // 48: team_service.GroupService.CreateInvite:output_type -> team_service.CreateInviteResponse
	15, // 49: team_service.GroupService.AcceptInvite:output_type -> team_service.AcceptInviteResponse
	19, // 50: team_service.GroupService.GetSimpleUserByGroupID:output_type -> team_service.GetSimpleUserByGroupIDResponse
	23, // 51: team_service.GroupService.GeneratePresignedURLs:output_type -> team_service.GeneratePresignedURLsResponse
	39, // [39:52] is the sub-list for method output_type
	26, // [26:39] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_team_service_group_proto_init() }
func file_team_service_group_proto_init() {
	if File_team_service_group_proto != nil {
		return
	}
	file_team_service_common_team_proto_init()
	file_team_service_group_proto_msgTypes[0].OneofWrappers = []any{}
	file_team_service_group_proto_msgTypes[1].OneofWrappers = []any{}
	file_team_service_group_proto_msgTypes[2].OneofWrappers = []any{}
	file_team_service_group_proto_msgTypes[3].OneofWrappers = []any{}
	file_team_service_group_proto_msgTypes[4].OneofWrappers = []any{}
	file_team_service_group_proto_msgTypes[5].OneofWrappers = []any{}
	file_team_service_group_proto_msgTypes[7].OneofWrappers = []any{}
	file_team_service_group_proto_msgTypes[9].OneofWrappers = []any{}
	file_team_service_group_proto_msgTypes[11].OneofWrappers = []any{}
	file_team_service_group_proto_msgTypes[12].OneofWrappers = []any{}
	file_team_service_group_proto_msgTypes[13].OneofWrappers = []any{}
	file_team_service_group_proto_msgTypes[15].OneofWrappers = []any{}
	file_team_service_group_proto_msgTypes[16].OneofWrappers = []any{}
	file_team_service_group_proto_msgTypes[18].OneofWrappers = []any{}
	file_team_service_group_proto_msgTypes[19].OneofWrappers = []any{}
	file_team_service_group_proto_msgTypes[23].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_team_service_group_proto_rawDesc), len(file_team_service_group_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_team_service_group_proto_goTypes,
		DependencyIndexes: file_team_service_group_proto_depIdxs,
		MessageInfos:      file_team_service_group_proto_msgTypes,
	}.Build()
	File_team_service_group_proto = out.File
	file_team_service_group_proto_goTypes = nil
	file_team_service_group_proto_depIdxs = nil
}
