// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: team_service/sprint.proto

package team_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	common "team_service/proto/common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SprintService_CreateSprint_FullMethodName       = "/team_service.SprintService/CreateSprint"
	SprintService_GetSprint_FullMethodName          = "/team_service.SprintService/GetSprint"
	SprintService_ListSprints_FullMethodName        = "/team_service.SprintService/ListSprints"
	SprintService_UpdateSprint_FullMethodName       = "/team_service.SprintService/UpdateSprint"
	SprintService_UpdateSprintStatus_FullMethodName = "/team_service.SprintService/UpdateSprintStatus"
	SprintService_DeleteSprint_FullMethodName       = "/team_service.SprintService/DeleteSprint"
	SprintService_GetSimpleSprints_FullMethodName   = "/team_service.SprintService/GetSimpleSprints"
	SprintService_ExportSprint_FullMethodName       = "/team_service.SprintService/ExportSprint"
)

// SprintServiceClient is the client API for SprintService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Sprint service handles operations related to sprints in a group.
type SprintServiceClient interface {
	CreateSprint(ctx context.Context, in *CreateSprintRequest, opts ...grpc.CallOption) (*CreateSprintResponse, error)
	GetSprint(ctx context.Context, in *common.IDRequest, opts ...grpc.CallOption) (*GetSprintResponse, error)
	ListSprints(ctx context.Context, in *ListSprintsRequest, opts ...grpc.CallOption) (*ListSprintsResponse, error)
	UpdateSprint(ctx context.Context, in *UpdateSprintRequest, opts ...grpc.CallOption) (*UpdateSprintResponse, error)
	UpdateSprintStatus(ctx context.Context, in *UpdateSprintStatusRequest, opts ...grpc.CallOption) (*UpdateSprintStatusResponse, error)
	DeleteSprint(ctx context.Context, in *common.IDRequest, opts ...grpc.CallOption) (*DeleteSprintResponse, error)
	GetSimpleSprints(ctx context.Context, in *common.IDRequest, opts ...grpc.CallOption) (*GetSimpleSprintsResponse, error)
	ExportSprint(ctx context.Context, in *common.IDRequest, opts ...grpc.CallOption) (*ExportSprintResponse, error)
}

type sprintServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSprintServiceClient(cc grpc.ClientConnInterface) SprintServiceClient {
	return &sprintServiceClient{cc}
}

func (c *sprintServiceClient) CreateSprint(ctx context.Context, in *CreateSprintRequest, opts ...grpc.CallOption) (*CreateSprintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSprintResponse)
	err := c.cc.Invoke(ctx, SprintService_CreateSprint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sprintServiceClient) GetSprint(ctx context.Context, in *common.IDRequest, opts ...grpc.CallOption) (*GetSprintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSprintResponse)
	err := c.cc.Invoke(ctx, SprintService_GetSprint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sprintServiceClient) ListSprints(ctx context.Context, in *ListSprintsRequest, opts ...grpc.CallOption) (*ListSprintsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSprintsResponse)
	err := c.cc.Invoke(ctx, SprintService_ListSprints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sprintServiceClient) UpdateSprint(ctx context.Context, in *UpdateSprintRequest, opts ...grpc.CallOption) (*UpdateSprintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSprintResponse)
	err := c.cc.Invoke(ctx, SprintService_UpdateSprint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sprintServiceClient) UpdateSprintStatus(ctx context.Context, in *UpdateSprintStatusRequest, opts ...grpc.CallOption) (*UpdateSprintStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSprintStatusResponse)
	err := c.cc.Invoke(ctx, SprintService_UpdateSprintStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sprintServiceClient) DeleteSprint(ctx context.Context, in *common.IDRequest, opts ...grpc.CallOption) (*DeleteSprintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSprintResponse)
	err := c.cc.Invoke(ctx, SprintService_DeleteSprint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sprintServiceClient) GetSimpleSprints(ctx context.Context, in *common.IDRequest, opts ...grpc.CallOption) (*GetSimpleSprintsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSimpleSprintsResponse)
	err := c.cc.Invoke(ctx, SprintService_GetSimpleSprints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sprintServiceClient) ExportSprint(ctx context.Context, in *common.IDRequest, opts ...grpc.CallOption) (*ExportSprintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportSprintResponse)
	err := c.cc.Invoke(ctx, SprintService_ExportSprint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SprintServiceServer is the server API for SprintService service.
// All implementations must embed UnimplementedSprintServiceServer
// for forward compatibility.
//
// Sprint service handles operations related to sprints in a group.
type SprintServiceServer interface {
	CreateSprint(context.Context, *CreateSprintRequest) (*CreateSprintResponse, error)
	GetSprint(context.Context, *common.IDRequest) (*GetSprintResponse, error)
	ListSprints(context.Context, *ListSprintsRequest) (*ListSprintsResponse, error)
	UpdateSprint(context.Context, *UpdateSprintRequest) (*UpdateSprintResponse, error)
	UpdateSprintStatus(context.Context, *UpdateSprintStatusRequest) (*UpdateSprintStatusResponse, error)
	DeleteSprint(context.Context, *common.IDRequest) (*DeleteSprintResponse, error)
	GetSimpleSprints(context.Context, *common.IDRequest) (*GetSimpleSprintsResponse, error)
	ExportSprint(context.Context, *common.IDRequest) (*ExportSprintResponse, error)
	mustEmbedUnimplementedSprintServiceServer()
}

// UnimplementedSprintServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSprintServiceServer struct{}

func (UnimplementedSprintServiceServer) CreateSprint(context.Context, *CreateSprintRequest) (*CreateSprintResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSprint not implemented")
}
func (UnimplementedSprintServiceServer) GetSprint(context.Context, *common.IDRequest) (*GetSprintResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSprint not implemented")
}
func (UnimplementedSprintServiceServer) ListSprints(context.Context, *ListSprintsRequest) (*ListSprintsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSprints not implemented")
}
func (UnimplementedSprintServiceServer) UpdateSprint(context.Context, *UpdateSprintRequest) (*UpdateSprintResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSprint not implemented")
}
func (UnimplementedSprintServiceServer) UpdateSprintStatus(context.Context, *UpdateSprintStatusRequest) (*UpdateSprintStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSprintStatus not implemented")
}
func (UnimplementedSprintServiceServer) DeleteSprint(context.Context, *common.IDRequest) (*DeleteSprintResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSprint not implemented")
}
func (UnimplementedSprintServiceServer) GetSimpleSprints(context.Context, *common.IDRequest) (*GetSimpleSprintsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSimpleSprints not implemented")
}
func (UnimplementedSprintServiceServer) ExportSprint(context.Context, *common.IDRequest) (*ExportSprintResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportSprint not implemented")
}
func (UnimplementedSprintServiceServer) mustEmbedUnimplementedSprintServiceServer() {}
func (UnimplementedSprintServiceServer) testEmbeddedByValue()                       {}

// UnsafeSprintServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SprintServiceServer will
// result in compilation errors.
type UnsafeSprintServiceServer interface {
	mustEmbedUnimplementedSprintServiceServer()
}

func RegisterSprintServiceServer(s grpc.ServiceRegistrar, srv SprintServiceServer) {
	// If the following call pancis, it indicates UnimplementedSprintServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SprintService_ServiceDesc, srv)
}

func _SprintService_CreateSprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSprintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SprintServiceServer).CreateSprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SprintService_CreateSprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SprintServiceServer).CreateSprint(ctx, req.(*CreateSprintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SprintService_GetSprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SprintServiceServer).GetSprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SprintService_GetSprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SprintServiceServer).GetSprint(ctx, req.(*common.IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SprintService_ListSprints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSprintsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SprintServiceServer).ListSprints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SprintService_ListSprints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SprintServiceServer).ListSprints(ctx, req.(*ListSprintsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SprintService_UpdateSprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSprintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SprintServiceServer).UpdateSprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SprintService_UpdateSprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SprintServiceServer).UpdateSprint(ctx, req.(*UpdateSprintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SprintService_UpdateSprintStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSprintStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SprintServiceServer).UpdateSprintStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SprintService_UpdateSprintStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SprintServiceServer).UpdateSprintStatus(ctx, req.(*UpdateSprintStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SprintService_DeleteSprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SprintServiceServer).DeleteSprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SprintService_DeleteSprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SprintServiceServer).DeleteSprint(ctx, req.(*common.IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SprintService_GetSimpleSprints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SprintServiceServer).GetSimpleSprints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SprintService_GetSimpleSprints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SprintServiceServer).GetSimpleSprints(ctx, req.(*common.IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SprintService_ExportSprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SprintServiceServer).ExportSprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SprintService_ExportSprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SprintServiceServer).ExportSprint(ctx, req.(*common.IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SprintService_ServiceDesc is the grpc.ServiceDesc for SprintService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SprintService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "team_service.SprintService",
	HandlerType: (*SprintServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSprint",
			Handler:    _SprintService_CreateSprint_Handler,
		},
		{
			MethodName: "GetSprint",
			Handler:    _SprintService_GetSprint_Handler,
		},
		{
			MethodName: "ListSprints",
			Handler:    _SprintService_ListSprints_Handler,
		},
		{
			MethodName: "UpdateSprint",
			Handler:    _SprintService_UpdateSprint_Handler,
		},
		{
			MethodName: "UpdateSprintStatus",
			Handler:    _SprintService_UpdateSprintStatus_Handler,
		},
		{
			MethodName: "DeleteSprint",
			Handler:    _SprintService_DeleteSprint_Handler,
		},
		{
			MethodName: "GetSimpleSprints",
			Handler:    _SprintService_GetSimpleSprints_Handler,
		},
		{
			MethodName: "ExportSprint",
			Handler:    _SprintService_ExportSprint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "team_service/sprint.proto",
}
