// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: team_service/sprint.proto

package team_service

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

// SprintServiceClient is the client API for SprintService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Sprint service handles operations related to sprints in a group.
type SprintServiceClient interface {
}

type sprintServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSprintServiceClient(cc grpc.ClientConnInterface) SprintServiceClient {
	return &sprintServiceClient{cc}
}

// SprintServiceServer is the server API for SprintService service.
// All implementations must embed UnimplementedSprintServiceServer
// for forward compatibility.
//
// Sprint service handles operations related to sprints in a group.
type SprintServiceServer interface {
	mustEmbedUnimplementedSprintServiceServer()
}

// UnimplementedSprintServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSprintServiceServer struct{}

func (UnimplementedSprintServiceServer) mustEmbedUnimplementedSprintServiceServer() {}
func (UnimplementedSprintServiceServer) testEmbeddedByValue()                       {}

// UnsafeSprintServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SprintServiceServer will
// result in compilation errors.
type UnsafeSprintServiceServer interface {
	mustEmbedUnimplementedSprintServiceServer()
}

func RegisterSprintServiceServer(s grpc.ServiceRegistrar, srv SprintServiceServer) {
	// If the following call pancis, it indicates UnimplementedSprintServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SprintService_ServiceDesc, srv)
}

// SprintService_ServiceDesc is the grpc.ServiceDesc for SprintService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SprintService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "team_service.SprintService",
	HandlerType: (*SprintServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "team_service/sprint.proto",
}
