// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: team_service/sprint.proto

package team_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "team_service/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSprintRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Goal          *string                `protobuf:"bytes,3,opt,name=goal,proto3,oneof" json:"goal"`
	StartDate     *Date                  `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date"`
	EndDate       *Date                  `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSprintRequest) Reset() {
	*x = CreateSprintRequest{}
	mi := &file_team_service_sprint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSprintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSprintRequest) ProtoMessage() {}

func (x *CreateSprintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_sprint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSprintRequest.ProtoReflect.Descriptor instead.
func (*CreateSprintRequest) Descriptor() ([]byte, []int) {
	return file_team_service_sprint_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSprintRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *CreateSprintRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSprintRequest) GetGoal() string {
	if x != nil && x.Goal != nil {
		return *x.Goal
	}
	return ""
}

func (x *CreateSprintRequest) GetStartDate() *Date {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *CreateSprintRequest) GetEndDate() *Date {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type CreateSprintResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sprint        *SprintMessage         `protobuf:"bytes,1,opt,name=sprint,proto3" json:"sprint"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSprintResponse) Reset() {
	*x = CreateSprintResponse{}
	mi := &file_team_service_sprint_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSprintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSprintResponse) ProtoMessage() {}

func (x *CreateSprintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_sprint_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSprintResponse.ProtoReflect.Descriptor instead.
func (*CreateSprintResponse) Descriptor() ([]byte, []int) {
	return file_team_service_sprint_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSprintResponse) GetSprint() *SprintMessage {
	if x != nil {
		return x.Sprint
	}
	return nil
}

func (x *CreateSprintResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetSprintResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sprint        *SprintMessage         `protobuf:"bytes,1,opt,name=sprint,proto3" json:"sprint"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSprintResponse) Reset() {
	*x = GetSprintResponse{}
	mi := &file_team_service_sprint_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSprintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSprintResponse) ProtoMessage() {}

func (x *GetSprintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_sprint_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSprintResponse.ProtoReflect.Descriptor instead.
func (*GetSprintResponse) Descriptor() ([]byte, []int) {
	return file_team_service_sprint_proto_rawDescGZIP(), []int{2}
}

func (x *GetSprintResponse) GetSprint() *SprintMessage {
	if x != nil {
		return x.Sprint
	}
	return nil
}

func (x *GetSprintResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type ListSprintsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSprintsRequest) Reset() {
	*x = ListSprintsRequest{}
	mi := &file_team_service_sprint_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSprintsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSprintsRequest) ProtoMessage() {}

func (x *ListSprintsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_sprint_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSprintsRequest.ProtoReflect.Descriptor instead.
func (*ListSprintsRequest) Descriptor() ([]byte, []int) {
	return file_team_service_sprint_proto_rawDescGZIP(), []int{3}
}

func (x *ListSprintsRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type ListSprintsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sprints       []*SprintMessage       `protobuf:"bytes,1,rep,name=sprints,proto3" json:"sprints"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total"`
	Error         *Error                 `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSprintsResponse) Reset() {
	*x = ListSprintsResponse{}
	mi := &file_team_service_sprint_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSprintsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSprintsResponse) ProtoMessage() {}

func (x *ListSprintsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_sprint_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSprintsResponse.ProtoReflect.Descriptor instead.
func (*ListSprintsResponse) Descriptor() ([]byte, []int) {
	return file_team_service_sprint_proto_rawDescGZIP(), []int{4}
}

func (x *ListSprintsResponse) GetSprints() []*SprintMessage {
	if x != nil {
		return x.Sprints
	}
	return nil
}

func (x *ListSprintsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListSprintsResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type UpdateSprintRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name"`
	Goal          *string                `protobuf:"bytes,3,opt,name=goal,proto3,oneof" json:"goal"`
	StartDate     *Date                  `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3,oneof" json:"start_date"`
	EndDate       *Date                  `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3,oneof" json:"end_date"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSprintRequest) Reset() {
	*x = UpdateSprintRequest{}
	mi := &file_team_service_sprint_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSprintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSprintRequest) ProtoMessage() {}

func (x *UpdateSprintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_sprint_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSprintRequest.ProtoReflect.Descriptor instead.
func (*UpdateSprintRequest) Descriptor() ([]byte, []int) {
	return file_team_service_sprint_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateSprintRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSprintRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateSprintRequest) GetGoal() string {
	if x != nil && x.Goal != nil {
		return *x.Goal
	}
	return ""
}

func (x *UpdateSprintRequest) GetStartDate() *Date {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *UpdateSprintRequest) GetEndDate() *Date {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type UpdateSprintResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sprint        *SprintMessage         `protobuf:"bytes,1,opt,name=sprint,proto3" json:"sprint"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSprintResponse) Reset() {
	*x = UpdateSprintResponse{}
	mi := &file_team_service_sprint_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSprintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSprintResponse) ProtoMessage() {}

func (x *UpdateSprintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_sprint_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSprintResponse.ProtoReflect.Descriptor instead.
func (*UpdateSprintResponse) Descriptor() ([]byte, []int) {
	return file_team_service_sprint_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateSprintResponse) GetSprint() *SprintMessage {
	if x != nil {
		return x.Sprint
	}
	return nil
}

func (x *UpdateSprintResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type UpdateSprintStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Status        SprintStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=team_service.SprintStatus" json:"status"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSprintStatusRequest) Reset() {
	*x = UpdateSprintStatusRequest{}
	mi := &file_team_service_sprint_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSprintStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSprintStatusRequest) ProtoMessage() {}

func (x *UpdateSprintStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_sprint_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSprintStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateSprintStatusRequest) Descriptor() ([]byte, []int) {
	return file_team_service_sprint_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateSprintStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSprintStatusRequest) GetStatus() SprintStatus {
	if x != nil {
		return x.Status
	}
	return SprintStatus_SPRINT_STATUS_UNSPECIFIED
}

type UpdateSprintStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Status        SprintStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=team_service.SprintStatus" json:"status"`
	Error         *Error                 `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSprintStatusResponse) Reset() {
	*x = UpdateSprintStatusResponse{}
	mi := &file_team_service_sprint_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSprintStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSprintStatusResponse) ProtoMessage() {}

func (x *UpdateSprintStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_sprint_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSprintStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateSprintStatusResponse) Descriptor() ([]byte, []int) {
	return file_team_service_sprint_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateSprintStatusResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSprintStatusResponse) GetStatus() SprintStatus {
	if x != nil {
		return x.Status
	}
	return SprintStatus_SPRINT_STATUS_UNSPECIFIED
}

func (x *UpdateSprintStatusResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type DeleteSprintResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSprintResponse) Reset() {
	*x = DeleteSprintResponse{}
	mi := &file_team_service_sprint_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSprintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSprintResponse) ProtoMessage() {}

func (x *DeleteSprintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_sprint_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSprintResponse.ProtoReflect.Descriptor instead.
func (*DeleteSprintResponse) Descriptor() ([]byte, []int) {
	return file_team_service_sprint_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteSprintResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteSprintResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetSimpleSprintsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sprints       []*SimpleSprintMessage `protobuf:"bytes,1,rep,name=sprints,proto3" json:"sprints"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSimpleSprintsResponse) Reset() {
	*x = GetSimpleSprintsResponse{}
	mi := &file_team_service_sprint_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSimpleSprintsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSimpleSprintsResponse) ProtoMessage() {}

func (x *GetSimpleSprintsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_sprint_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSimpleSprintsResponse.ProtoReflect.Descriptor instead.
func (*GetSimpleSprintsResponse) Descriptor() ([]byte, []int) {
	return file_team_service_sprint_proto_rawDescGZIP(), []int{10}
}

func (x *GetSimpleSprintsResponse) GetSprints() []*SimpleSprintMessage {
	if x != nil {
		return x.Sprints
	}
	return nil
}

func (x *GetSimpleSprintsResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type ExportSprintResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          []byte                 `protobuf:"bytes,1,opt,name=file,proto3" json:"file"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type"`
	Error         *Error                 `protobuf:"bytes,4,opt,name=error,proto3,oneof" json:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportSprintResponse) Reset() {
	*x = ExportSprintResponse{}
	mi := &file_team_service_sprint_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportSprintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportSprintResponse) ProtoMessage() {}

func (x *ExportSprintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_sprint_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportSprintResponse.ProtoReflect.Descriptor instead.
func (*ExportSprintResponse) Descriptor() ([]byte, []int) {
	return file_team_service_sprint_proto_rawDescGZIP(), []int{11}
}

func (x *ExportSprintResponse) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *ExportSprintResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ExportSprintResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ExportSprintResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type DeleteDraftSprintsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDraftSprintsResponse) Reset() {
	*x = DeleteDraftSprintsResponse{}
	mi := &file_team_service_sprint_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDraftSprintsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDraftSprintsResponse) ProtoMessage() {}

func (x *DeleteDraftSprintsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_sprint_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDraftSprintsResponse.ProtoReflect.Descriptor instead.
func (*DeleteDraftSprintsResponse) Descriptor() ([]byte, []int) {
	return file_team_service_sprint_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteDraftSprintsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteDraftSprintsResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_team_service_sprint_proto protoreflect.FileDescriptor

const file_team_service_sprint_proto_rawDesc = "" +
	"\n" +
	"\x19team_service/sprint.proto\x12\fteam_service\x1a\x12common/error.proto\x1a\x13common/common.proto\x1a\x1eteam_service/common.team.proto\"\xc8\x01\n" +
	"\x13CreateSprintRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\x04goal\x18\x03 \x01(\tH\x00R\x04goal\x88\x01\x01\x121\n" +
	"\n" +
	"start_date\x18\x04 \x01(\v2\x12.team_service.DateR\tstartDate\x12-\n" +
	"\bend_date\x18\x05 \x01(\v2\x12.team_service.DateR\aendDateB\a\n" +
	"\x05_goal\"\x85\x01\n" +
	"\x14CreateSprintResponse\x123\n" +
	"\x06sprint\x18\x01 \x01(\v2\x1b.team_service.SprintMessageR\x06sprint\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x13.team_service.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\x82\x01\n" +
	"\x11GetSprintResponse\x123\n" +
	"\x06sprint\x18\x01 \x01(\v2\x1b.team_service.SprintMessageR\x06sprint\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x13.team_service.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"/\n" +
	"\x12ListSprintsRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\"\x9c\x01\n" +
	"\x13ListSprintsResponse\x125\n" +
	"\asprints\x18\x01 \x03(\v2\x1b.team_service.SprintMessageR\asprints\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12.\n" +
	"\x05error\x18\x03 \x01(\v2\x13.team_service.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\xf1\x01\n" +
	"\x13UpdateSprintRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x17\n" +
	"\x04goal\x18\x03 \x01(\tH\x01R\x04goal\x88\x01\x01\x126\n" +
	"\n" +
	"start_date\x18\x04 \x01(\v2\x12.team_service.DateH\x02R\tstartDate\x88\x01\x01\x122\n" +
	"\bend_date\x18\x05 \x01(\v2\x12.team_service.DateH\x03R\aendDate\x88\x01\x01B\a\n" +
	"\x05_nameB\a\n" +
	"\x05_goalB\r\n" +
	"\v_start_dateB\v\n" +
	"\t_end_date\"\x85\x01\n" +
	"\x14UpdateSprintResponse\x123\n" +
	"\x06sprint\x18\x01 \x01(\v2\x1b.team_service.SprintMessageR\x06sprint\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x13.team_service.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"_\n" +
	"\x19UpdateSprintStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x122\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1a.team_service.SprintStatusR\x06status\"\x9a\x01\n" +
	"\x1aUpdateSprintStatusResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x122\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1a.team_service.SprintStatusR\x06status\x12.\n" +
	"\x05error\x18\x03 \x01(\v2\x13.team_service.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"j\n" +
	"\x14DeleteSprintResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x13.team_service.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\x91\x01\n" +
	"\x18GetSimpleSprintsResponse\x12;\n" +
	"\asprints\x18\x01 \x03(\v2!.team_service.SimpleSprintMessageR\asprints\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x13.team_service.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\xa3\x01\n" +
	"\x14ExportSprintResponse\x12\x12\n" +
	"\x04file\x18\x01 \x01(\fR\x04file\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12.\n" +
	"\x05error\x18\x04 \x01(\v2\x13.team_service.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"p\n" +
	"\x1aDeleteDraftSprintsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x13.team_service.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error2\xeb\x05\n" +
	"\rSprintService\x12U\n" +
	"\fCreateSprint\x12!.team_service.CreateSprintRequest\x1a\".team_service.CreateSprintResponse\x12?\n" +
	"\tGetSprint\x12\x11.common.IDRequest\x1a\x1f.team_service.GetSprintResponse\x12R\n" +
	"\vListSprints\x12 .team_service.ListSprintsRequest\x1a!.team_service.ListSprintsResponse\x12U\n" +
	"\fUpdateSprint\x12!.team_service.UpdateSprintRequest\x1a\".team_service.UpdateSprintResponse\x12g\n" +
	"\x12UpdateSprintStatus\x12'.team_service.UpdateSprintStatusRequest\x1a(.team_service.UpdateSprintStatusResponse\x12E\n" +
	"\fDeleteSprint\x12\x11.common.IDRequest\x1a\".team_service.DeleteSprintResponse\x12M\n" +
	"\x10GetSimpleSprints\x12\x11.common.IDRequest\x1a&.team_service.GetSimpleSprintsResponse\x12E\n" +
	"\fExportSprint\x12\x11.common.IDRequest\x1a\".team_service.ExportSprintResponse\x12Q\n" +
	"\x12DeleteDraftSprints\x12\x11.common.IDRequest\x1a(.team_service.DeleteDraftSprintsResponseB\x14Z\x12proto/team_serviceb\x06proto3"

var (
	file_team_service_sprint_proto_rawDescOnce sync.Once
	file_team_service_sprint_proto_rawDescData []byte
)

func file_team_service_sprint_proto_rawDescGZIP() []byte {
	file_team_service_sprint_proto_rawDescOnce.Do(func() {
		file_team_service_sprint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_team_service_sprint_proto_rawDesc), len(file_team_service_sprint_proto_rawDesc)))
	})
	return file_team_service_sprint_proto_rawDescData
}

var file_team_service_sprint_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_team_service_sprint_proto_goTypes = []any{
	(*CreateSprintRequest)(nil),        // 0: team_service.CreateSprintRequest
	(*CreateSprintResponse)(nil),       // 1: team_service.CreateSprintResponse
	(*GetSprintResponse)(nil),          // 2: team_service.GetSprintResponse
	(*ListSprintsRequest)(nil),         // 3: team_service.ListSprintsRequest
	(*ListSprintsResponse)(nil),        // 4: team_service.ListSprintsResponse
	(*UpdateSprintRequest)(nil),        // 5: team_service.UpdateSprintRequest
	(*UpdateSprintResponse)(nil),       // 6: team_service.UpdateSprintResponse
	(*UpdateSprintStatusRequest)(nil),  // 7: team_service.UpdateSprintStatusRequest
	(*UpdateSprintStatusResponse)(nil), // 8: team_service.UpdateSprintStatusResponse
	(*DeleteSprintResponse)(nil),       // 9: team_service.DeleteSprintResponse
	(*GetSimpleSprintsResponse)(nil),   // 10: team_service.GetSimpleSprintsResponse
	(*ExportSprintResponse)(nil),       // 11: team_service.ExportSprintResponse
	(*DeleteDraftSprintsResponse)(nil), // 12: team_service.DeleteDraftSprintsResponse
	(*Date)(nil),                       // 13: team_service.Date
	(*SprintMessage)(nil),              // 14: team_service.SprintMessage
	(*Error)(nil),                      // 15: team_service.Error
	(SprintStatus)(0),                  // 16: team_service.SprintStatus
	(*SimpleSprintMessage)(nil),        // 17: team_service.SimpleSprintMessage
	(*common.IDRequest)(nil),           // 18: common.IDRequest
}
var file_team_service_sprint_proto_depIdxs = []int32{
	13, // 0: team_service.CreateSprintRequest.start_date:type_name -> team_service.Date
	13, // 1: team_service.CreateSprintRequest.end_date:type_name -> team_service.Date
	14, // 2: team_service.CreateSprintResponse.sprint:type_name -> team_service.SprintMessage
	15, // 3: team_service.CreateSprintResponse.error:type_name -> team_service.Error
	14, // 4: team_service.GetSprintResponse.sprint:type_name -> team_service.SprintMessage
	15, // 5: team_service.GetSprintResponse.error:type_name -> team_service.Error
	14, // 6: team_service.ListSprintsResponse.sprints:type_name -> team_service.SprintMessage
	15, // 7: team_service.ListSprintsResponse.error:type_name -> team_service.Error
	13, // 8: team_service.UpdateSprintRequest.start_date:type_name -> team_service.Date
	13, // 9: team_service.UpdateSprintRequest.end_date:type_name -> team_service.Date
	14, // 10: team_service.UpdateSprintResponse.sprint:type_name -> team_service.SprintMessage
	15, // 11: team_service.UpdateSprintResponse.error:type_name -> team_service.Error
	16, // 12: team_service.UpdateSprintStatusRequest.status:type_name -> team_service.SprintStatus
	16, // 13: team_service.UpdateSprintStatusResponse.status:type_name -> team_service.SprintStatus
	15, // 14: team_service.UpdateSprintStatusResponse.error:type_name -> team_service.Error
	15, // 15: team_service.DeleteSprintResponse.error:type_name -> team_service.Error
	17, // 16: team_service.GetSimpleSprintsResponse.sprints:type_name -> team_service.SimpleSprintMessage
	15, // 17: team_service.GetSimpleSprintsResponse.error:type_name -> team_service.Error
	15, // 18: team_service.ExportSprintResponse.error:type_name -> team_service.Error
	15, // 19: team_service.DeleteDraftSprintsResponse.error:type_name -> team_service.Error
	0,  // 20: team_service.SprintService.CreateSprint:input_type -> team_service.CreateSprintRequest
	18, // 21: team_service.SprintService.GetSprint:input_type -> common.IDRequest
	3,  // 22: team_service.SprintService.ListSprints:input_type -> team_service.ListSprintsRequest
	5,  // 23: team_service.SprintService.UpdateSprint:input_type -> team_service.UpdateSprintRequest
	7,  // 24: team_service.SprintService.UpdateSprintStatus:input_type -> team_service.UpdateSprintStatusRequest
	18, // 25: team_service.SprintService.DeleteSprint:input_type -> common.IDRequest
	18, // 26: team_service.SprintService.GetSimpleSprints:input_type -> common.IDRequest
	18, // 27: team_service.SprintService.ExportSprint:input_type -> common.IDRequest
	18, // 28: team_service.SprintService.DeleteDraftSprints:input_type -> common.IDRequest
	1,  // 29: team_service.SprintService.CreateSprint:output_type -> team_service.CreateSprintResponse
	2,  // 30: team_service.SprintService.GetSprint:output_type -> team_service.GetSprintResponse
	4,  // 31: team_service.SprintService.ListSprints:output_type -> team_service.ListSprintsResponse
	6,  // 32: team_service.SprintService.UpdateSprint:output_type -> team_service.UpdateSprintResponse
	8,  // 33: team_service.SprintService.UpdateSprintStatus:output_type -> team_service.UpdateSprintStatusResponse
	9,  // 34: team_service.SprintService.DeleteSprint:output_type -> team_service.DeleteSprintResponse
	10, // 35: team_service.SprintService.GetSimpleSprints:output_type -> team_service.GetSimpleSprintsResponse
	11, // 36: team_service.SprintService.ExportSprint:output_type -> team_service.ExportSprintResponse
	12, // 37: team_service.SprintService.DeleteDraftSprints:output_type -> team_service.DeleteDraftSprintsResponse
	29, // [29:38] is the sub-list for method output_type
	20, // [20:29] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_team_service_sprint_proto_init() }
func file_team_service_sprint_proto_init() {
	if File_team_service_sprint_proto != nil {
		return
	}
	file_team_service_common_team_proto_init()
	file_team_service_sprint_proto_msgTypes[0].OneofWrappers = []any{}
	file_team_service_sprint_proto_msgTypes[1].OneofWrappers = []any{}
	file_team_service_sprint_proto_msgTypes[2].OneofWrappers = []any{}
	file_team_service_sprint_proto_msgTypes[4].OneofWrappers = []any{}
	file_team_service_sprint_proto_msgTypes[5].OneofWrappers = []any{}
	file_team_service_sprint_proto_msgTypes[6].OneofWrappers = []any{}
	file_team_service_sprint_proto_msgTypes[8].OneofWrappers = []any{}
	file_team_service_sprint_proto_msgTypes[9].OneofWrappers = []any{}
	file_team_service_sprint_proto_msgTypes[10].OneofWrappers = []any{}
	file_team_service_sprint_proto_msgTypes[11].OneofWrappers = []any{}
	file_team_service_sprint_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_team_service_sprint_proto_rawDesc), len(file_team_service_sprint_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_team_service_sprint_proto_goTypes,
		DependencyIndexes: file_team_service_sprint_proto_depIdxs,
		MessageInfos:      file_team_service_sprint_proto_msgTypes,
	}.Build()
	File_team_service_sprint_proto = out.File
	file_team_service_sprint_proto_goTypes = nil
	file_team_service_sprint_proto_depIdxs = nil
}
