// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: team_service/user.proto

package team_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	common "team_service/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserInfoResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Email                string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email"`
	UseEmailNotification bool                   `protobuf:"varint,2,opt,name=use_email_notification,json=useEmailNotification,proto3" json:"use_email_notification"`
	UseAppNotification   bool                   `protobuf:"varint,3,opt,name=use_app_notification,json=useAppNotification,proto3" json:"use_app_notification"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	Error                *Error                 `protobuf:"bytes,5,opt,name=error,proto3,oneof" json:"error"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetUserInfoResponse) Reset() {
	*x = GetUserInfoResponse{}
	mi := &file_team_service_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResponse) ProtoMessage() {}

func (x *GetUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_team_service_user_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserInfoResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetUserInfoResponse) GetUseEmailNotification() bool {
	if x != nil {
		return x.UseEmailNotification
	}
	return false
}

func (x *GetUserInfoResponse) GetUseAppNotification() bool {
	if x != nil {
		return x.UseAppNotification
	}
	return false
}

func (x *GetUserInfoResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetUserInfoResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type NotificationConfigurationRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UseEmailNotification bool                   `protobuf:"varint,1,opt,name=use_email_notification,json=useEmailNotification,proto3" json:"use_email_notification"`
	UseAppNotification   *bool                  `protobuf:"varint,2,opt,name=use_app_notification,json=useAppNotification,proto3,oneof" json:"use_app_notification"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *NotificationConfigurationRequest) Reset() {
	*x = NotificationConfigurationRequest{}
	mi := &file_team_service_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationConfigurationRequest) ProtoMessage() {}

func (x *NotificationConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationConfigurationRequest.ProtoReflect.Descriptor instead.
func (*NotificationConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_team_service_user_proto_rawDescGZIP(), []int{1}
}

func (x *NotificationConfigurationRequest) GetUseEmailNotification() bool {
	if x != nil {
		return x.UseEmailNotification
	}
	return false
}

func (x *NotificationConfigurationRequest) GetUseAppNotification() bool {
	if x != nil && x.UseAppNotification != nil {
		return *x.UseAppNotification
	}
	return false
}

type NotificationConfigurationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationConfigurationResponse) Reset() {
	*x = NotificationConfigurationResponse{}
	mi := &file_team_service_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationConfigurationResponse) ProtoMessage() {}

func (x *NotificationConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationConfigurationResponse.ProtoReflect.Descriptor instead.
func (*NotificationConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_team_service_user_proto_rawDescGZIP(), []int{2}
}

func (x *NotificationConfigurationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *NotificationConfigurationResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_team_service_user_proto protoreflect.FileDescriptor

const file_team_service_user_proto_rawDesc = "" +
	"\n" +
	"\x17team_service/user.proto\x12\fteam_service\x1a\x1eteam_service/common.team.proto\x1a\x13common/common.proto\x1a\x12common/error.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x88\x02\n" +
	"\x13GetUserInfoResponse\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x124\n" +
	"\x16use_email_notification\x18\x02 \x01(\bR\x14useEmailNotification\x120\n" +
	"\x14use_app_notification\x18\x03 \x01(\bR\x12useAppNotification\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12.\n" +
	"\x05error\x18\x05 \x01(\v2\x13.team_service.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\xa8\x01\n" +
	" NotificationConfigurationRequest\x124\n" +
	"\x16use_email_notification\x18\x01 \x01(\bR\x14useEmailNotification\x125\n" +
	"\x14use_app_notification\x18\x02 \x01(\bH\x00R\x12useAppNotification\x88\x01\x01B\x17\n" +
	"\x15_use_app_notification\"w\n" +
	"!NotificationConfigurationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x13.team_service.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error2\xd3\x01\n" +
	"\vUserService\x12F\n" +
	"\vGetUserInfo\x12\x14.common.EmptyRequest\x1a!.team_service.GetUserInfoResponse\x12|\n" +
	"\x19NotificationConfiguration\x12..team_service.NotificationConfigurationRequest\x1a/.team_service.NotificationConfigurationResponseB\x14Z\x12proto/team_serviceb\x06proto3"

var (
	file_team_service_user_proto_rawDescOnce sync.Once
	file_team_service_user_proto_rawDescData []byte
)

func file_team_service_user_proto_rawDescGZIP() []byte {
	file_team_service_user_proto_rawDescOnce.Do(func() {
		file_team_service_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_team_service_user_proto_rawDesc), len(file_team_service_user_proto_rawDesc)))
	})
	return file_team_service_user_proto_rawDescData
}

var file_team_service_user_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_team_service_user_proto_goTypes = []any{
	(*GetUserInfoResponse)(nil),               // 0: team_service.GetUserInfoResponse
	(*NotificationConfigurationRequest)(nil),  // 1: team_service.NotificationConfigurationRequest
	(*NotificationConfigurationResponse)(nil), // 2: team_service.NotificationConfigurationResponse
	(*timestamppb.Timestamp)(nil),             // 3: google.protobuf.Timestamp
	(*Error)(nil),                             // 4: team_service.Error
	(*common.EmptyRequest)(nil),               // 5: common.EmptyRequest
}
var file_team_service_user_proto_depIdxs = []int32{
	3, // 0: team_service.GetUserInfoResponse.created_at:type_name -> google.protobuf.Timestamp
	4, // 1: team_service.GetUserInfoResponse.error:type_name -> team_service.Error
	4, // 2: team_service.NotificationConfigurationResponse.error:type_name -> team_service.Error
	5, // 3: team_service.UserService.GetUserInfo:input_type -> common.EmptyRequest
	1, // 4: team_service.UserService.NotificationConfiguration:input_type -> team_service.NotificationConfigurationRequest
	0, // 5: team_service.UserService.GetUserInfo:output_type -> team_service.GetUserInfoResponse
	2, // 6: team_service.UserService.NotificationConfiguration:output_type -> team_service.NotificationConfigurationResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_team_service_user_proto_init() }
func file_team_service_user_proto_init() {
	if File_team_service_user_proto != nil {
		return
	}
	file_team_service_common_team_proto_init()
	file_team_service_user_proto_msgTypes[0].OneofWrappers = []any{}
	file_team_service_user_proto_msgTypes[1].OneofWrappers = []any{}
	file_team_service_user_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_team_service_user_proto_rawDesc), len(file_team_service_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_team_service_user_proto_goTypes,
		DependencyIndexes: file_team_service_user_proto_depIdxs,
		MessageInfos:      file_team_service_user_proto_msgTypes,
	}.Build()
	File_team_service_user_proto = out.File
	file_team_service_user_proto_goTypes = nil
	file_team_service_user_proto_depIdxs = nil
}
