// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: team_service/work.proto

package team_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	common "team_service/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateWorkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	Description   *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description"`
	SprintId      *string                `protobuf:"bytes,3,opt,name=sprint_id,json=sprintId,proto3,oneof" json:"sprint_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkRequest) Reset() {
	*x = CreateWorkRequest{}
	mi := &file_team_service_work_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkRequest) ProtoMessage() {}

func (x *CreateWorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_work_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkRequest) Descriptor() ([]byte, []int) {
	return file_team_service_work_proto_rawDescGZIP(), []int{0}
}

func (x *CreateWorkRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWorkRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateWorkRequest) GetSprintId() string {
	if x != nil && x.SprintId != nil {
		return *x.SprintId
	}
	return ""
}

type CreateWorkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Work          *WorkMessage           `protobuf:"bytes,1,opt,name=work,proto3" json:"work"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkResponse) Reset() {
	*x = CreateWorkResponse{}
	mi := &file_team_service_work_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkResponse) ProtoMessage() {}

func (x *CreateWorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_work_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkResponse.ProtoReflect.Descriptor instead.
func (*CreateWorkResponse) Descriptor() ([]byte, []int) {
	return file_team_service_work_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWorkResponse) GetWork() *WorkMessage {
	if x != nil {
		return x.Work
	}
	return nil
}

func (x *CreateWorkResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetWorkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Work          *WorkMessage           `protobuf:"bytes,1,opt,name=work,proto3" json:"work"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkResponse) Reset() {
	*x = GetWorkResponse{}
	mi := &file_team_service_work_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkResponse) ProtoMessage() {}

func (x *GetWorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_work_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkResponse.ProtoReflect.Descriptor instead.
func (*GetWorkResponse) Descriptor() ([]byte, []int) {
	return file_team_service_work_proto_rawDescGZIP(), []int{2}
}

func (x *GetWorkResponse) GetWork() *WorkMessage {
	if x != nil {
		return x.Work
	}
	return nil
}

func (x *GetWorkResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type ListWorksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SprintId      *string                `protobuf:"bytes,1,opt,name=sprint_id,json=sprintId,proto3,oneof" json:"sprint_id"`
	AssigneeId    *string                `protobuf:"bytes,2,opt,name=assignee_id,json=assigneeId,proto3,oneof" json:"assignee_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorksRequest) Reset() {
	*x = ListWorksRequest{}
	mi := &file_team_service_work_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorksRequest) ProtoMessage() {}

func (x *ListWorksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_work_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorksRequest.ProtoReflect.Descriptor instead.
func (*ListWorksRequest) Descriptor() ([]byte, []int) {
	return file_team_service_work_proto_rawDescGZIP(), []int{3}
}

func (x *ListWorksRequest) GetSprintId() string {
	if x != nil && x.SprintId != nil {
		return *x.SprintId
	}
	return ""
}

func (x *ListWorksRequest) GetAssigneeId() string {
	if x != nil && x.AssigneeId != nil {
		return *x.AssigneeId
	}
	return ""
}

type ListWorksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Works         []*WorkMessage         `protobuf:"bytes,1,rep,name=works,proto3" json:"works"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorksResponse) Reset() {
	*x = ListWorksResponse{}
	mi := &file_team_service_work_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorksResponse) ProtoMessage() {}

func (x *ListWorksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_work_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorksResponse.ProtoReflect.Descriptor instead.
func (*ListWorksResponse) Descriptor() ([]byte, []int) {
	return file_team_service_work_proto_rawDescGZIP(), []int{4}
}

func (x *ListWorksResponse) GetWorks() []*WorkMessage {
	if x != nil {
		return x.Works
	}
	return nil
}

func (x *ListWorksResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type UpdateWorkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description"`
	AssigneeId    *string                `protobuf:"bytes,4,opt,name=assignee_id,json=assigneeId,proto3,oneof" json:"assignee_id"`
	IsUnassigned  *bool                  `protobuf:"varint,5,opt,name=is_unassigned,json=isUnassigned,proto3,oneof" json:"is_unassigned"`
	StoryPoint    *int32                 `protobuf:"varint,6,opt,name=story_point,json=storyPoint,proto3,oneof" json:"story_point"`
	DueDate       *Date                  `protobuf:"bytes,7,opt,name=due_date,json=dueDate,proto3,oneof" json:"due_date"`
	Priority      *WorkPriority          `protobuf:"varint,8,opt,name=priority,proto3,enum=team_service.WorkPriority,oneof" json:"priority"`
	Status        *WorkStatus            `protobuf:"varint,9,opt,name=status,proto3,enum=team_service.WorkStatus,oneof" json:"status"`
	SprintId      *string                `protobuf:"bytes,10,opt,name=sprint_id,json=sprintId,proto3,oneof" json:"sprint_id"`
	IsUnsetSprint *bool                  `protobuf:"varint,11,opt,name=is_unset_sprint,json=isUnsetSprint,proto3,oneof" json:"is_unset_sprint"`
	Version       int32                  `protobuf:"varint,12,opt,name=version,proto3" json:"version"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorkRequest) Reset() {
	*x = UpdateWorkRequest{}
	mi := &file_team_service_work_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkRequest) ProtoMessage() {}

func (x *UpdateWorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_work_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkRequest.ProtoReflect.Descriptor instead.
func (*UpdateWorkRequest) Descriptor() ([]byte, []int) {
	return file_team_service_work_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateWorkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateWorkRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateWorkRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateWorkRequest) GetAssigneeId() string {
	if x != nil && x.AssigneeId != nil {
		return *x.AssigneeId
	}
	return ""
}

func (x *UpdateWorkRequest) GetIsUnassigned() bool {
	if x != nil && x.IsUnassigned != nil {
		return *x.IsUnassigned
	}
	return false
}

func (x *UpdateWorkRequest) GetStoryPoint() int32 {
	if x != nil && x.StoryPoint != nil {
		return *x.StoryPoint
	}
	return 0
}

func (x *UpdateWorkRequest) GetDueDate() *Date {
	if x != nil {
		return x.DueDate
	}
	return nil
}

func (x *UpdateWorkRequest) GetPriority() WorkPriority {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return WorkPriority_WORK_PRIORITY_UNSPECIFIED
}

func (x *UpdateWorkRequest) GetStatus() WorkStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return WorkStatus_WORK_STATUS_UNSPECIFIED
}

func (x *UpdateWorkRequest) GetSprintId() string {
	if x != nil && x.SprintId != nil {
		return *x.SprintId
	}
	return ""
}

func (x *UpdateWorkRequest) GetIsUnsetSprint() bool {
	if x != nil && x.IsUnsetSprint != nil {
		return *x.IsUnsetSprint
	}
	return false
}

func (x *UpdateWorkRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type UpdateWorkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Work          *WorkMessage           `protobuf:"bytes,1,opt,name=work,proto3" json:"work"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorkResponse) Reset() {
	*x = UpdateWorkResponse{}
	mi := &file_team_service_work_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkResponse) ProtoMessage() {}

func (x *UpdateWorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_work_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkResponse.ProtoReflect.Descriptor instead.
func (*UpdateWorkResponse) Descriptor() ([]byte, []int) {
	return file_team_service_work_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateWorkResponse) GetWork() *WorkMessage {
	if x != nil {
		return x.Work
	}
	return nil
}

func (x *UpdateWorkResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type DeleteWorkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkResponse) Reset() {
	*x = DeleteWorkResponse{}
	mi := &file_team_service_work_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkResponse) ProtoMessage() {}

func (x *DeleteWorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_work_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkResponse.ProtoReflect.Descriptor instead.
func (*DeleteWorkResponse) Descriptor() ([]byte, []int) {
	return file_team_service_work_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteWorkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteWorkResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type CreateChecklistItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkId        string                 `protobuf:"bytes,1,opt,name=work_id,json=workId,proto3" json:"work_id"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChecklistItemRequest) Reset() {
	*x = CreateChecklistItemRequest{}
	mi := &file_team_service_work_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChecklistItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChecklistItemRequest) ProtoMessage() {}

func (x *CreateChecklistItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_work_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChecklistItemRequest.ProtoReflect.Descriptor instead.
func (*CreateChecklistItemRequest) Descriptor() ([]byte, []int) {
	return file_team_service_work_proto_rawDescGZIP(), []int{8}
}

func (x *CreateChecklistItemRequest) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

func (x *CreateChecklistItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateChecklistItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *ChecklistItemMessage  `protobuf:"bytes,1,opt,name=item,proto3" json:"item"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChecklistItemResponse) Reset() {
	*x = CreateChecklistItemResponse{}
	mi := &file_team_service_work_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChecklistItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChecklistItemResponse) ProtoMessage() {}

func (x *CreateChecklistItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_work_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChecklistItemResponse.ProtoReflect.Descriptor instead.
func (*CreateChecklistItemResponse) Descriptor() ([]byte, []int) {
	return file_team_service_work_proto_rawDescGZIP(), []int{9}
}

func (x *CreateChecklistItemResponse) GetItem() *ChecklistItemMessage {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *CreateChecklistItemResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type UpdateChecklistItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name"`
	IsCompleted   *bool                  `protobuf:"varint,3,opt,name=is_completed,json=isCompleted,proto3,oneof" json:"is_completed"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChecklistItemRequest) Reset() {
	*x = UpdateChecklistItemRequest{}
	mi := &file_team_service_work_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChecklistItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChecklistItemRequest) ProtoMessage() {}

func (x *UpdateChecklistItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_work_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChecklistItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateChecklistItemRequest) Descriptor() ([]byte, []int) {
	return file_team_service_work_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateChecklistItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateChecklistItemRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateChecklistItemRequest) GetIsCompleted() bool {
	if x != nil && x.IsCompleted != nil {
		return *x.IsCompleted
	}
	return false
}

type UpdateChecklistItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checklist     *ChecklistItemMessage  `protobuf:"bytes,1,opt,name=checklist,proto3" json:"checklist"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChecklistItemResponse) Reset() {
	*x = UpdateChecklistItemResponse{}
	mi := &file_team_service_work_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChecklistItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChecklistItemResponse) ProtoMessage() {}

func (x *UpdateChecklistItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_work_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChecklistItemResponse.ProtoReflect.Descriptor instead.
func (*UpdateChecklistItemResponse) Descriptor() ([]byte, []int) {
	return file_team_service_work_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateChecklistItemResponse) GetChecklist() *ChecklistItemMessage {
	if x != nil {
		return x.Checklist
	}
	return nil
}

func (x *UpdateChecklistItemResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type DeleteChecklistItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checklist     *ChecklistItemMessage  `protobuf:"bytes,1,opt,name=checklist,proto3" json:"checklist"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChecklistItemResponse) Reset() {
	*x = DeleteChecklistItemResponse{}
	mi := &file_team_service_work_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChecklistItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChecklistItemResponse) ProtoMessage() {}

func (x *DeleteChecklistItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_work_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChecklistItemResponse.ProtoReflect.Descriptor instead.
func (*DeleteChecklistItemResponse) Descriptor() ([]byte, []int) {
	return file_team_service_work_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteChecklistItemResponse) GetChecklist() *ChecklistItemMessage {
	if x != nil {
		return x.Checklist
	}
	return nil
}

func (x *DeleteChecklistItemResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type CreateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkId        string                 `protobuf:"bytes,1,opt,name=work_id,json=workId,proto3" json:"work_id"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentRequest) Reset() {
	*x = CreateCommentRequest{}
	mi := &file_team_service_work_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentRequest) ProtoMessage() {}

func (x *CreateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_work_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return file_team_service_work_proto_rawDescGZIP(), []int{13}
}

func (x *CreateCommentRequest) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

func (x *CreateCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CreateCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *CommentListMessage    `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentResponse) Reset() {
	*x = CreateCommentResponse{}
	mi := &file_team_service_work_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentResponse) ProtoMessage() {}

func (x *CreateCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_work_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentResponse.ProtoReflect.Descriptor instead.
func (*CreateCommentResponse) Descriptor() ([]byte, []int) {
	return file_team_service_work_proto_rawDescGZIP(), []int{14}
}

func (x *CreateCommentResponse) GetComment() *CommentListMessage {
	if x != nil {
		return x.Comment
	}
	return nil
}

func (x *CreateCommentResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type DeleteCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *CommentListMessage    `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentResponse) Reset() {
	*x = DeleteCommentResponse{}
	mi := &file_team_service_work_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentResponse) ProtoMessage() {}

func (x *DeleteCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_work_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentResponse.ProtoReflect.Descriptor instead.
func (*DeleteCommentResponse) Descriptor() ([]byte, []int) {
	return file_team_service_work_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteCommentResponse) GetComment() *CommentListMessage {
	if x != nil {
		return x.Comment
	}
	return nil
}

func (x *DeleteCommentResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type UpdateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommentRequest) Reset() {
	*x = UpdateCommentRequest{}
	mi := &file_team_service_work_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentRequest) ProtoMessage() {}

func (x *UpdateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_work_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentRequest.ProtoReflect.Descriptor instead.
func (*UpdateCommentRequest) Descriptor() ([]byte, []int) {
	return file_team_service_work_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateCommentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type UpdateCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *CommentListMessage    `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommentResponse) Reset() {
	*x = UpdateCommentResponse{}
	mi := &file_team_service_work_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentResponse) ProtoMessage() {}

func (x *UpdateCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_team_service_work_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentResponse.ProtoReflect.Descriptor instead.
func (*UpdateCommentResponse) Descriptor() ([]byte, []int) {
	return file_team_service_work_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateCommentResponse) GetComment() *CommentListMessage {
	if x != nil {
		return x.Comment
	}
	return nil
}

func (x *UpdateCommentResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_team_service_work_proto protoreflect.FileDescriptor

const file_team_service_work_proto_rawDesc = "" +
	"\n" +
	"\x17team_service/work.proto\x12\fteam_service\x1a\x12common/error.proto\x1a\x13common/common.proto\x1a\x1eteam_service/common.team.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x8e\x01\n" +
	"\x11CreateWorkRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x12 \n" +
	"\tsprint_id\x18\x03 \x01(\tH\x01R\bsprintId\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\f\n" +
	"\n" +
	"_sprint_id\"}\n" +
	"\x12CreateWorkResponse\x12-\n" +
	"\x04work\x18\x01 \x01(\v2\x19.team_service.WorkMessageR\x04work\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x13.team_service.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"z\n" +
	"\x0fGetWorkResponse\x12-\n" +
	"\x04work\x18\x01 \x01(\v2\x19.team_service.WorkMessageR\x04work\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x13.team_service.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"x\n" +
	"\x10ListWorksRequest\x12 \n" +
	"\tsprint_id\x18\x01 \x01(\tH\x00R\bsprintId\x88\x01\x01\x12$\n" +
	"\vassignee_id\x18\x02 \x01(\tH\x01R\n" +
	"assigneeId\x88\x01\x01B\f\n" +
	"\n" +
	"_sprint_idB\x0e\n" +
	"\f_assignee_id\"~\n" +
	"\x11ListWorksResponse\x12/\n" +
	"\x05works\x18\x01 \x03(\v2\x19.team_service.WorkMessageR\x05works\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x13.team_service.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\xfc\x04\n" +
	"\x11UpdateWorkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12$\n" +
	"\vassignee_id\x18\x04 \x01(\tH\x02R\n" +
	"assigneeId\x88\x01\x01\x12(\n" +
	"\ris_unassigned\x18\x05 \x01(\bH\x03R\fisUnassigned\x88\x01\x01\x12$\n" +
	"\vstory_point\x18\x06 \x01(\x05H\x04R\n" +
	"storyPoint\x88\x01\x01\x122\n" +
	"\bdue_date\x18\a \x01(\v2\x12.team_service.DateH\x05R\adueDate\x88\x01\x01\x12;\n" +
	"\bpriority\x18\b \x01(\x0e2\x1a.team_service.WorkPriorityH\x06R\bpriority\x88\x01\x01\x125\n" +
	"\x06status\x18\t \x01(\x0e2\x18.team_service.WorkStatusH\aR\x06status\x88\x01\x01\x12 \n" +
	"\tsprint_id\x18\n" +
	" \x01(\tH\bR\bsprintId\x88\x01\x01\x12+\n" +
	"\x0fis_unset_sprint\x18\v \x01(\bH\tR\risUnsetSprint\x88\x01\x01\x12\x18\n" +
	"\aversion\x18\f \x01(\x05R\aversionB\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\x0e\n" +
	"\f_assignee_idB\x10\n" +
	"\x0e_is_unassignedB\x0e\n" +
	"\f_story_pointB\v\n" +
	"\t_due_dateB\v\n" +
	"\t_priorityB\t\n" +
	"\a_statusB\f\n" +
	"\n" +
	"_sprint_idB\x12\n" +
	"\x10_is_unset_sprint\"}\n" +
	"\x12UpdateWorkResponse\x12-\n" +
	"\x04work\x18\x01 \x01(\v2\x19.team_service.WorkMessageR\x04work\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x13.team_service.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"h\n" +
	"\x12DeleteWorkResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x13.team_service.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"I\n" +
	"\x1aCreateChecklistItemRequest\x12\x17\n" +
	"\awork_id\x18\x01 \x01(\tR\x06workId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x8f\x01\n" +
	"\x1bCreateChecklistItemResponse\x126\n" +
	"\x04item\x18\x01 \x01(\v2\".team_service.ChecklistItemMessageR\x04item\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x13.team_service.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\x87\x01\n" +
	"\x1aUpdateChecklistItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12&\n" +
	"\fis_completed\x18\x03 \x01(\bH\x01R\visCompleted\x88\x01\x01B\a\n" +
	"\x05_nameB\x0f\n" +
	"\r_is_completed\"\x99\x01\n" +
	"\x1bUpdateChecklistItemResponse\x12@\n" +
	"\tchecklist\x18\x01 \x01(\v2\".team_service.ChecklistItemMessageR\tchecklist\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x13.team_service.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\x99\x01\n" +
	"\x1bDeleteChecklistItemResponse\x12@\n" +
	"\tchecklist\x18\x01 \x01(\v2\".team_service.ChecklistItemMessageR\tchecklist\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x13.team_service.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"I\n" +
	"\x14CreateCommentRequest\x12\x17\n" +
	"\awork_id\x18\x01 \x01(\tR\x06workId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\x8d\x01\n" +
	"\x15CreateCommentResponse\x12:\n" +
	"\acomment\x18\x01 \x01(\v2 .team_service.CommentListMessageR\acomment\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x13.team_service.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\x8d\x01\n" +
	"\x15DeleteCommentResponse\x12:\n" +
	"\acomment\x18\x01 \x01(\v2 .team_service.CommentListMessageR\acomment\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x13.team_service.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"@\n" +
	"\x14UpdateCommentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\x8d\x01\n" +
	"\x15UpdateCommentResponse\x12:\n" +
	"\acomment\x18\x01 \x01(\v2 .team_service.CommentListMessageR\acomment\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x13.team_service.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error2\xa7\a\n" +
	"\vWorkService\x12O\n" +
	"\n" +
	"CreateWork\x12\x1f.team_service.CreateWorkRequest\x1a .team_service.CreateWorkResponse\x12;\n" +
	"\aGetWork\x12\x11.common.IDRequest\x1a\x1d.team_service.GetWorkResponse\x12L\n" +
	"\tListWorks\x12\x1e.team_service.ListWorksRequest\x1a\x1f.team_service.ListWorksResponse\x12O\n" +
	"\n" +
	"UpdateWork\x12\x1f.team_service.UpdateWorkRequest\x1a .team_service.UpdateWorkResponse\x12A\n" +
	"\n" +
	"DeleteWork\x12\x11.common.IDRequest\x1a .team_service.DeleteWorkResponse\x12j\n" +
	"\x13CreateChecklistItem\x12(.team_service.CreateChecklistItemRequest\x1a).team_service.CreateChecklistItemResponse\x12j\n" +
	"\x13UpdateChecklistItem\x12(.team_service.UpdateChecklistItemRequest\x1a).team_service.UpdateChecklistItemResponse\x12S\n" +
	"\x13DeleteChecklistItem\x12\x11.common.IDRequest\x1a).team_service.DeleteChecklistItemResponse\x12X\n" +
	"\rCreateComment\x12\".team_service.CreateCommentRequest\x1a#.team_service.CreateCommentResponse\x12X\n" +
	"\rUpdateComment\x12\".team_service.UpdateCommentRequest\x1a#.team_service.UpdateCommentResponse\x12G\n" +
	"\rDeleteComment\x12\x11.common.IDRequest\x1a#.team_service.DeleteCommentResponseB\x14Z\x12proto/team_serviceb\x06proto3"

var (
	file_team_service_work_proto_rawDescOnce sync.Once
	file_team_service_work_proto_rawDescData []byte
)

func file_team_service_work_proto_rawDescGZIP() []byte {
	file_team_service_work_proto_rawDescOnce.Do(func() {
		file_team_service_work_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_team_service_work_proto_rawDesc), len(file_team_service_work_proto_rawDesc)))
	})
	return file_team_service_work_proto_rawDescData
}

var file_team_service_work_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_team_service_work_proto_goTypes = []any{
	(*CreateWorkRequest)(nil),           // 0: team_service.CreateWorkRequest
	(*CreateWorkResponse)(nil),          // 1: team_service.CreateWorkResponse
	(*GetWorkResponse)(nil),             // 2: team_service.GetWorkResponse
	(*ListWorksRequest)(nil),            // 3: team_service.ListWorksRequest
	(*ListWorksResponse)(nil),           // 4: team_service.ListWorksResponse
	(*UpdateWorkRequest)(nil),           // 5: team_service.UpdateWorkRequest
	(*UpdateWorkResponse)(nil),          // 6: team_service.UpdateWorkResponse
	(*DeleteWorkResponse)(nil),          // 7: team_service.DeleteWorkResponse
	(*CreateChecklistItemRequest)(nil),  // 8: team_service.CreateChecklistItemRequest
	(*CreateChecklistItemResponse)(nil), // 9: team_service.CreateChecklistItemResponse
	(*UpdateChecklistItemRequest)(nil),  // 10: team_service.UpdateChecklistItemRequest
	(*UpdateChecklistItemResponse)(nil), // 11: team_service.UpdateChecklistItemResponse
	(*DeleteChecklistItemResponse)(nil), // 12: team_service.DeleteChecklistItemResponse
	(*CreateCommentRequest)(nil),        // 13: team_service.CreateCommentRequest
	(*CreateCommentResponse)(nil),       // 14: team_service.CreateCommentResponse
	(*DeleteCommentResponse)(nil),       // 15: team_service.DeleteCommentResponse
	(*UpdateCommentRequest)(nil),        // 16: team_service.UpdateCommentRequest
	(*UpdateCommentResponse)(nil),       // 17: team_service.UpdateCommentResponse
	(*WorkMessage)(nil),                 // 18: team_service.WorkMessage
	(*Error)(nil),                       // 19: team_service.Error
	(*Date)(nil),                        // 20: team_service.Date
	(WorkPriority)(0),                   // 21: team_service.WorkPriority
	(WorkStatus)(0),                     // 22: team_service.WorkStatus
	(*ChecklistItemMessage)(nil),        // 23: team_service.ChecklistItemMessage
	(*CommentListMessage)(nil),          // 24: team_service.CommentListMessage
	(*common.IDRequest)(nil),            // 25: common.IDRequest
}
var file_team_service_work_proto_depIdxs = []int32{
	18, // 0: team_service.CreateWorkResponse.work:type_name -> team_service.WorkMessage
	19, // 1: team_service.CreateWorkResponse.error:type_name -> team_service.Error
	18, // 2: team_service.GetWorkResponse.work:type_name -> team_service.WorkMessage
	19, // 3: team_service.GetWorkResponse.error:type_name -> team_service.Error
	18, // 4: team_service.ListWorksResponse.works:type_name -> team_service.WorkMessage
	19, // 5: team_service.ListWorksResponse.error:type_name -> team_service.Error
	20, // 6: team_service.UpdateWorkRequest.due_date:type_name -> team_service.Date
	21, // 7: team_service.UpdateWorkRequest.priority:type_name -> team_service.WorkPriority
	22, // 8: team_service.UpdateWorkRequest.status:type_name -> team_service.WorkStatus
	18, // 9: team_service.UpdateWorkResponse.work:type_name -> team_service.WorkMessage
	19, // 10: team_service.UpdateWorkResponse.error:type_name -> team_service.Error
	19, // 11: team_service.DeleteWorkResponse.error:type_name -> team_service.Error
	23, // 12: team_service.CreateChecklistItemResponse.item:type_name -> team_service.ChecklistItemMessage
	19, // 13: team_service.CreateChecklistItemResponse.error:type_name -> team_service.Error
	23, // 14: team_service.UpdateChecklistItemResponse.checklist:type_name -> team_service.ChecklistItemMessage
	19, // 15: team_service.UpdateChecklistItemResponse.error:type_name -> team_service.Error
	23, // 16: team_service.DeleteChecklistItemResponse.checklist:type_name -> team_service.ChecklistItemMessage
	19, // 17: team_service.DeleteChecklistItemResponse.error:type_name -> team_service.Error
	24, // 18: team_service.CreateCommentResponse.comment:type_name -> team_service.CommentListMessage
	19, // 19: team_service.CreateCommentResponse.error:type_name -> team_service.Error
	24, // 20: team_service.DeleteCommentResponse.comment:type_name -> team_service.CommentListMessage
	19, // 21: team_service.DeleteCommentResponse.error:type_name -> team_service.Error
	24, // 22: team_service.UpdateCommentResponse.comment:type_name -> team_service.CommentListMessage
	19, // 23: team_service.UpdateCommentResponse.error:type_name -> team_service.Error
	0,  // 24: team_service.WorkService.CreateWork:input_type -> team_service.CreateWorkRequest
	25, // 25: team_service.WorkService.GetWork:input_type -> common.IDRequest
	3,  // 26: team_service.WorkService.ListWorks:input_type -> team_service.ListWorksRequest
	5,  // 27: team_service.WorkService.UpdateWork:input_type -> team_service.UpdateWorkRequest
	25, // 28: team_service.WorkService.DeleteWork:input_type -> common.IDRequest
	8,  // 29: team_service.WorkService.CreateChecklistItem:input_type -> team_service.CreateChecklistItemRequest
	10, // 30: team_service.WorkService.UpdateChecklistItem:input_type -> team_service.UpdateChecklistItemRequest
	25, // 31: team_service.WorkService.DeleteChecklistItem:input_type -> common.IDRequest
	13, // 32: team_service.WorkService.CreateComment:input_type -> team_service.CreateCommentRequest
	16, // 33: team_service.WorkService.UpdateComment:input_type -> team_service.UpdateCommentRequest
	25, // 34: team_service.WorkService.DeleteComment:input_type -> common.IDRequest
	1,  // 35: team_service.WorkService.CreateWork:output_type -> team_service.CreateWorkResponse
	2,  // 36: team_service.WorkService.GetWork:output_type -> team_service.GetWorkResponse
	4,  // 37: team_service.WorkService.ListWorks:output_type -> team_service.ListWorksResponse
	6,  // 38: team_service.WorkService.UpdateWork:output_type -> team_service.UpdateWorkResponse
	7,  // 39: team_service.WorkService.DeleteWork:output_type -> team_service.DeleteWorkResponse
	9,  // 40: team_service.WorkService.CreateChecklistItem:output_type -> team_service.CreateChecklistItemResponse
	11, // 41: team_service.WorkService.UpdateChecklistItem:output_type -> team_service.UpdateChecklistItemResponse
	12, // 42: team_service.WorkService.DeleteChecklistItem:output_type -> team_service.DeleteChecklistItemResponse
	14, // 43: team_service.WorkService.CreateComment:output_type -> team_service.CreateCommentResponse
	17, // 44: team_service.WorkService.UpdateComment:output_type -> team_service.UpdateCommentResponse
	15, // 45: team_service.WorkService.DeleteComment:output_type -> team_service.DeleteCommentResponse
	35, // [35:46] is the sub-list for method output_type
	24, // [24:35] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_team_service_work_proto_init() }
func file_team_service_work_proto_init() {
	if File_team_service_work_proto != nil {
		return
	}
	file_team_service_common_team_proto_init()
	file_team_service_work_proto_msgTypes[0].OneofWrappers = []any{}
	file_team_service_work_proto_msgTypes[1].OneofWrappers = []any{}
	file_team_service_work_proto_msgTypes[2].OneofWrappers = []any{}
	file_team_service_work_proto_msgTypes[3].OneofWrappers = []any{}
	file_team_service_work_proto_msgTypes[4].OneofWrappers = []any{}
	file_team_service_work_proto_msgTypes[5].OneofWrappers = []any{}
	file_team_service_work_proto_msgTypes[6].OneofWrappers = []any{}
	file_team_service_work_proto_msgTypes[7].OneofWrappers = []any{}
	file_team_service_work_proto_msgTypes[9].OneofWrappers = []any{}
	file_team_service_work_proto_msgTypes[10].OneofWrappers = []any{}
	file_team_service_work_proto_msgTypes[11].OneofWrappers = []any{}
	file_team_service_work_proto_msgTypes[12].OneofWrappers = []any{}
	file_team_service_work_proto_msgTypes[14].OneofWrappers = []any{}
	file_team_service_work_proto_msgTypes[15].OneofWrappers = []any{}
	file_team_service_work_proto_msgTypes[17].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_team_service_work_proto_rawDesc), len(file_team_service_work_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_team_service_work_proto_goTypes,
		DependencyIndexes: file_team_service_work_proto_depIdxs,
		MessageInfos:      file_team_service_work_proto_msgTypes,
	}.Build()
	File_team_service_work_proto = out.File
	file_team_service_work_proto_goTypes = nil
	file_team_service_work_proto_depIdxs = nil
}
