// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: team_service/work.proto

package team_service

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

// WorkServiceClient is the client API for WorkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WorkService handles operations related to works/tasks in a group.
type WorkServiceClient interface {
}

type workServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkServiceClient(cc grpc.ClientConnInterface) WorkServiceClient {
	return &workServiceClient{cc}
}

// WorkServiceServer is the server API for WorkService service.
// All implementations must embed UnimplementedWorkServiceServer
// for forward compatibility.
//
// WorkService handles operations related to works/tasks in a group.
type WorkServiceServer interface {
	mustEmbedUnimplementedWorkServiceServer()
}

// UnimplementedWorkServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkServiceServer struct{}

func (UnimplementedWorkServiceServer) mustEmbedUnimplementedWorkServiceServer() {}
func (UnimplementedWorkServiceServer) testEmbeddedByValue()                     {}

// UnsafeWorkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkServiceServer will
// result in compilation errors.
type UnsafeWorkServiceServer interface {
	mustEmbedUnimplementedWorkServiceServer()
}

func RegisterWorkServiceServer(s grpc.ServiceRegistrar, srv WorkServiceServer) {
	// If the following call pancis, it indicates UnimplementedWorkServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkService_ServiceDesc, srv)
}

// WorkService_ServiceDesc is the grpc.ServiceDesc for WorkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "team_service.WorkService",
	HandlerType: (*WorkServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "team_service/work.proto",
}
